OPM/opm-core

CMakeLists_files.cmake
opm/core/pressure/tpfa/cfs_tpfa_residual.c
opm/core/pressure/tpfa/ifs_tpfa.c
opm/core/simulator/WellState.hpp
opm/core/well_controls.h
opm/core/wells/WellsGroup.cpp
opm/core/wells/WellsManager.cpp
opm/core/wells/well_controls.c
tests/test_stoppedwells.cpp
tests/test_wellcontrols.cpp
tests/test_wellsmanager.cpp
tests/wells_manager_data_wellSTOP.data
tests/wells_stopped.data

With this PR the simulator distinguish between OPEN, STOP and SHUT wells. 
STOP: Well stopped off above the formation. The total rate is set to zero.  I.e. It allows for flow in the well.
SHUT: Well completely isolated from the formation. The well is removed
from the well list. 
This PR also contain a test case that check that the well rate is zero.
This is the last peace that is needed in order to run the full Norne deck. The results do not match satisfactory yet.

Add support for stopped wells

---

opm/core/wells/WellsManager_impl.hpp
tests/test_wellsmanager.cpp

With this PR the WellsManager will check the state of completions before adding them to the internal `struct wells` datastructure. Observe that the Parser/Schedule object does currently not respect  `WELOPEN` manipulations of completions and will return status `OPEN` anyway; work on proper support of `WELOPEN` in Parser/Schedule is underways.
With this PR the rest of the code should "just work" when the Parser has been updated. The current PR should do the job - but it is just a suggestion, other implementations are certainly possible.

Check completion state

---

opm/core/grid/MinpvProcessor.hpp

The non-template class MinpvProcessor contains all function
definitions inside of the header file without inlining. The
results in the symbols being in the library of opm-core and
in case of using CpGrid an addtional occurence in other
libraries (opm-autodiff?).
This commit changes this by simply inlining all these functions.
Note that another (better?) option would be to move at least
the bigger once into a cpp file.

Avoid multiple symbol definitions for MinPvProcessor.

---

CMakeLists_files.cmake
opm/core/io/OutputWriter.cpp
opm/core/io/OutputWriter.hpp
opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/EclipseWriter.hpp
opm/core/simulator/AdaptiveSimulatorTimer.cpp
opm/core/simulator/AdaptiveSimulatorTimer.hpp
opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/SimulatorTimer.cpp
opm/core/simulator/SimulatorTimer.hpp
opm/core/simulator/SimulatorTimerInterface.hpp

This PR introduces an interface for SimulatorTimers implemented by SimulatorTimer and AdaptiveSimulatorTimer. 
The EclipseWriter has been revised to support writing of substeps when used with the AdaptiveTimeStepping.
It has been tested with the SPE9 case and the solution as well as the dates look ok.

Introduce interface for SimulatorTimers and support writing of substeps with EclipseWriter.

---

opm/core/grid/GridHelpers.cpp
opm/core/grid/GridHelpers.hpp

To identify the face tag we use the iterator over the cell faces. This provides all the information needed both for UG and CpGrid.
For UG we can directly compute the half face index from by subtracting
```C++
&(*cellFaces()[0].begin())
```
from it. For `CpGrid` the iterator will provide the cell index and we will use Bard's proposal to compute the face tag correctly.
Supersedes and closes #719

Adds a free function to UgGridHelpers to access the face tag.

---

cmake/Modules/FindMETIS.cmake
cmake/Modules/FindZOLTAN.cmake
cmake/Modules/Finddune-alugrid.cmake
cmake/Modules/ewoms-prereqs.cmake

this PR contains a few smallish build system updates which enable ZOLTAN for alugrid, fix the METIS detection on some distributions and work around a dune 2.4 deprecation warning (the last patch is pretty hacky, but the dune build system does this in a similar way). most of the work was done by @dr-robertk.

Build system update

---

CMakeLists_files.cmake
examples/compute_tof.cpp
opm/core/pressure/IncompTpfaSinglePhase.cpp
opm/core/pressure/IncompTpfaSinglePhase.hpp
opm/core/props/IncompPropertiesSinglePhase.cpp
opm/core/props/IncompPropertiesSinglePhase.hpp
opm/core/tof/FlowDiagnostics.cpp
opm/core/tof/FlowDiagnostics.hpp
tests/test_flowdiagnostics.cpp

This PR collects the following features:
- `IncompTpfaSinglePhase` and `IncompPropertiesSinglePhase`, new classes intended to make it easy to run simplified diagnostic computations on more or less arbitrary cases.
- A rewritten `compute_tof` example program, that should now be able to run with deck input containing arbitrary number of phases and related properties (used to require 2-phase oil-water), using the above mentioned classes.
- New diagnostics functions `computeFandPhi()`, `computeLorenz()` and `computeSweep()` in `FlowDiagnostics.hpp` with unit tests.
While somewhat large, the PR contains no changes to existing features, other than to the compute_tof program. Some caveats relating to `compute_tof`:
- The `compute_tof` program treats the reservoir in a very simplified fashion: …

More features for flow diagnostics

---

opm/core/grid/GridManager.cpp
opm/core/grid/MinpvProcessor.hpp
tests/test_minpvprocessor.cpp

This changes significantly the volume of some cells after processing. Before this, large inactive cells with low or zero porosity could contribute large pore volumes to a simulation since their volumes could be added to active cells in MINPV processing.
Please report if this improves pore volume match, do not merge this (or its companion OPM/dune-cornerpoint#122) until it has been tested.

Make MinpvProcessor ignore inactive cells.

---

CMakeLists.txt
CMakeLists_files.cmake
opm/core/linalg/ParallelIstlInformation.hpp
tests/DuneIstlTestHelpers.hpp
tests/test_parallel_linearsolver.cpp
tests/test_parallelistlinformation.cpp

We need to compute quite a few global reductions in the Newton method of opm-autodiff. This commit adds the functionality to compute several reductions combined using only one global communication. Compiles and test succeeds with one or more process.
I have added a test for the reductions and moved some common functions with test_parallel_linearsolver.cpp to a new header DuneIstlTestHelper.hpp to prevent code duplication.

Added methods for computing global reductions.

---

opm/core/linalg/ParallelIstlInformation.hpp
tests/test_parallelistlinformation.cpp

Correctly compute the minimum and maximum values.
As there are no functors for computing the minimum and maximum,
we convert the std::max and std::min function pointers to
functors (which is not really nice.) Previously we were somehow
tricked into using std::greater and std::less, which of course do
return true or false and not what we need. Additionally, do more
excessive testing with different ranges.
This is a follow up to #728 that fixes some additional issues. Sorry for not finding this earlier.

Fixes global reductions

---

opm/core/wells/WellsManager_impl.hpp

Followup to: https://github.com/OPM/opm-parser/pull/402
Will use the parser Well->getRefDepth() for the well reference depth; the defaulted / not defaulted issues are left with the parser.

Using Parser to calculate well reference depth.

---

opm/core/simulator/AdaptiveSimulatorTimer.hpp
opm/core/simulator/SimulatorTimer.hpp
opm/core/simulator/SimulatorTimerInterface.hpp

This is the interface method for the previously used operator++ which cannot be made virtual since the return type differs.

Method advance for SimulatorTimers.

---

opm/core/simulator/BlackoilState.cpp

Maybe it was intended to not compare the rv states. It seems like a bug though.

BlackoilState: added forgotten rv variable to equal method.

---

opm/core/linalg/ParallelIstlInformation.hpp

* We need to compute the reductions on a const object and therefore this PR makes them const
* Eigen's containers have nor begin()/end() iterator access for whatever reason therefore we need
to rely on operator[] *sigh*

Constify parallelinformation and workaround Eigen's weirdness

---

opm/core/props/pvt/PvtConstCompr.hpp
opm/core/props/pvt/PvtDead.cpp
opm/core/props/pvt/PvtDead.hpp
opm/core/props/pvt/PvtDeadSpline.cpp
opm/core/props/pvt/PvtDeadSpline.hpp
opm/core/props/pvt/PvtLiveGas.cpp
opm/core/props/pvt/PvtLiveOil.cpp
opm/core/props/pvt/PvtLiveOil.hpp

This implements a temperature dependency of the oil and water viscosities according to the Eclipse documentation. (gas does not depend on temperature in E100 for some reason and we don't have a gas composition yet, so we also can't do the E300 approach.) After quite a bit of head-banging, I decided that I did not want to change the APIs for the PVT properties (which is only required once an energy conservation equation is implemented), and that only the viscosities are considered for now, i.e. densities are a job for another month...

PVT classes: implement temperature dependent viscosity

---

opm/core/wells/WellsManager.cpp
tests/test_wellsmanager.cpp

When no BHP limit is given for a producer, a BHP control is added anyway, with a limit of 1 atm.
This should solve issue OPM/opm-parser#441.

Add default producer BHP control when not given in deck.

---

opm/core/props/BlackoilPropertiesFromDeck.hpp
opm/core/simulator/BlackoilState.hpp
opm/core/simulator/SimulatorState.hpp

We need this for the parallel sim_fibo_ad_cp, where we will need to point to the same parts in two copies without duplicating data.

Makes BlackoilPropertiesFromDeck copyable.

---

CMakeLists_files.cmake
opm/core/simulator/AdaptiveSimulatorTimer.cpp
opm/core/simulator/AdaptiveSimulatorTimer.hpp
opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/TimeStepControl.cpp
opm/core/simulator/TimeStepControl.hpp

AdaptiveSimulatorTimer: -improvement in time step adjustment near end of time interval
-max time step parameter
PIDTimeStepControl --> TimeStepControl:
- added simple iteration count time step control
- bug fix in PIDAndIterationCountTimeStepControl
AdaptiveTimeStepping: apply the above changes.
New parameter: 
timestep.control=iterationcount (select simple iteration count time stepping)
timestep.max_timestep_in_days (max time step size in days)
timestep.control.decayrate (decrease time step if iteration count is to large, default 0.75)
timestep.control.growthrate (increase time step if iteration count is smaller than target, default 1.25)

Adaptive timestepping improvements. 

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp

removed initial_fraction, we use restart factor instead and one parameter less. 
Also, to suggest the time step for the next report interval we use the average of all timesteps used in this report interval. This seems to be a little bit less aggressive.

AdaptiveTimeStepping: improvements.

---

CMakeLists_files.cmake

The header opm/core/linalg/ParallelIstlInformation.hpp is not installed - then opm-autodiff fails when building against an installed version of opm-core.

Install ParallelIstlInformation.hpp

---

examples/compute_tof.cpp
opm/core/flowdiagnostics/FlowDiagnostics.cpp
opm/core/flowdiagnostics/FlowDiagnostics.hpp

This collects the following:
- a new function, `computeWellPairs()` that computes the pore volumes associated with each (injector, producer) pair,
- the `compute_tof` example program now always computes both forward (injector) and backward (producer) diagnostics (instead of that being a user option),
- `compute_tof` also calls `computeWellPairs()` and outputs the results, if tracer computations are asked for.
The new function does not have a unit test, but results have been found to be comparable to equivalent results from MRST.

Improvements for flow diagnostic tools

---

opm/core/linalg/LinearSolverIstl.cpp

Due to the size of the overlap layer and the discretization scheme
the rhs might not contain correct values for overlap cells. This
commit makes sure they are correct by an additional communication step.

Makes right hand side passed to linear solver consistent.

---

opm/core/utility/thresholdPressures.hpp

Using class SimulationConfig (from EclipseState) instead of Deck to get threshold pressure values. 
Tested on Norne.

OPM-166: Use SimulationConfig instead of Deck to get threshold pressure

---

opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/writeECLData.cpp
opm/core/props/pvt/PvtLiveOil.cpp
opm/core/simulator/TimeStepControl.cpp
opm/core/wells/WellsManager.cpp
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp
tests/test_writenumwells.cpp

This fixes warnings of various kinds, and removes an unneeded argument from the WellsManager constructor.
There are downstream consequences in opm-autodiff and opm-polymer, so companion PRs in those modules must be merged simultaneously with this one.

Fix warnings (and small API change)

---

opm/core/linalg/ParallelIstlInformation.hpp

Well, you never know. There are containers that use a signed integer
for storing its size. This results in a warning about comparing signed with
unsigned integers. This commit prevents this by explicitly casting the size
to std::size_t.

Prevents unsigned-signed-comparison warnings for container with signed size

---

opm/core/grid/GridHelpers.cpp
opm/core/grid/GridHelpers.hpp
opm/core/simulator/initStateEquil.hpp
opm/core/simulator/initStateEquil_impl.hpp

Currently the keyword EQUIL is not supported by the fully implicit blackoil simulator when using CpGrid. This commit is a first step towards this as it makes the implementation generic.

Ported initStateEquil to using the GridHelpers.

---

opm/core/grid.h

While minor, it could confuse users.
Closes #521.

Doc fix: face -> cell.

---

opm/core/simulator/initStateEquil_impl.hpp

Again related to anonymous namespace function only being used in template functions.

Fix unneeded-internal-declaration warning.

---

opm/core/grid/GridHelpers.cpp
opm/core/grid/GridHelpers.hpp

This PR moves all the grid helper functions that do not depend on Eigen to the module where the
grid is declared and implement.
This is the first out of three PRs that should be merged simultaneously.

Moves all functions that do not depend on Eigen to Opm::UgGridHelpers.  [1/3]

---

opm/core/io/eclipse/EclipseWriteRFTHandler.cpp
opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/EclipseWriter.hpp

This PR fixes the issue of having "monstrous" amount of data produced when sub stepping is enabled. Now, only the summary is written on sub steps.

Eclipsewriter: only write summary in substeps

---

opm/core/simulator/initState_impl.hpp

Cell argument can not be null for BlackoilPropertiesFromDeck class. This fixes a usage in the non-equilibrium initialisation code. Also, it makes it possible to initialise from a deck without RS or RV.

Fix property method calls.

---

cmake/Modules/Finddune-alugrid.cmake

first this makes the test very slow, second (and more importantly) it
makes the test fail on dune master as the header relies on the
presence of the DUNE_GRID_VERSION* macros which are not present at the
configure stage of the build...

FindAlugrid.cmake: do not try to include the whole grid

---

CMakeLists_files.cmake
opm/core/props/pvt/PvtConstCompr.hpp
opm/core/props/pvt/PvtDead.cpp
opm/core/props/pvt/PvtDead.hpp
opm/core/props/pvt/PvtDeadSpline.cpp
opm/core/props/pvt/PvtDeadSpline.hpp
opm/core/props/pvt/PvtLiveGas.cpp
opm/core/props/pvt/PvtLiveOil.cpp
opm/core/props/pvt/PvtLiveOil.hpp
opm/core/props/pvt/ThermalGasPvtWrapper.hpp
opm/core/props/pvt/ThermalOilPvtWrapper.hpp
opm/core/props/pvt/ThermalWaterPvtWrapper.hpp

this is the stuff which is required to implement a "pseudo thermal" black-oil simulator where the densities and viscosities are temperature dependent but energy is not conserved. This PR depends on OPM/opm-parser#427 to compile. for the code to have any effect the "plumbing" PR for opm-autodiff is required. (but autodiff compiles even without the latter.)
for what is worth this PR does not introduce any new ctest failures on my machine...

Implement temperature dependent density

---

opm/core/io/OutputWriter.cpp
opm/core/io/OutputWriter.hpp
opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/EclipseWriter.hpp
opm/core/simulator/SimulatorOutput.cpp
opm/core/simulator/SimulatorOutput.hpp
tests/test_EclipseWriteRFTHandler.cpp
tests/test_EclipseWriter.cpp
tests/test_writenumwells.cpp

And also fix up the start time used for summary output.
Note that this required a small `EclipseWriter` API change, so this PR must be merged synchronously with the corresponding opm-autodiff and opm-polymer PRs...

Use deck units for summary output

---

cmake/Modules/FindCXX11Features.cmake
cmake/Modules/opm-material-prereqs.cmake

this keyword is quite useful to avoid mistakes during development because the compiler will complain if it sees a method marked as 'final' which has not been declared 'virtual' in a base class...

FindCXX11Features.cmake: check for the c++-2011 "final" specifier

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

This happens when the time step is too large. A restart with smaller time step solves the problem. This is needed when Norne is run with AMG.

AdaptiveTimeStepping: also catch ISTLError caused in AMG.

---

opm/core/io/OutputWriter.cpp
opm/core/io/OutputWriter.hpp
opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/EclipseWriter.hpp
opm/core/simulator/SimulatorOutput.cpp
opm/core/simulator/SimulatorOutput.hpp
tests/test_EclipseWriteRFTHandler.cpp
tests/test_EclipseWriter.cpp
tests/test_writenumwells.cpp

seems like the guy who added EclipseState::getDeckUnitSystem() suffers
from dementia...
note that the ugly `handleUnit_()` method is still required as long as a correct "unit name" ought to be supported. (the conversion itself could equally well be done using opm-parser's unit handling code...)

summary output: use the EclipseState to determine the deck unit system

---

opm/core/io/eclipse/EclipseWriter.cpp

basically, the unit system was reversed for rates and a
UnitSystem::UnitType object was implicitly casted to bool for the
bottom hole pressure monitor. (if the BHP monitor worked, it was only
by accident...)

fix screw-up in the unit handling for the summary output

---

cmake/Modules/FindPETSc.cmake
cmake/Modules/opm-core-prereqs.cmake

Now building will no longer fail if PETSc isn't available, and it correctly
degrades if it cannot find an available MPI. It should now behave similarly as
other optionals, such as SuperLU.
A continuation of https://github.com/OPM/opm-core/pull/727, but with slightly reformulated goals. Now, instead of being an explicit USE_PETSC flag it rather just looks for it like other CMake Modules.

Cleans up PETSc detection

---

cmake/Modules/UseOptimization.cmake

-O3 is sometimes declared "unsafe"
(cf. https://wiki.gentoo.org/wiki/GCC_optimization ) and it seems like
it bit us in https://github.com/OPM/opm-material/issues/23 if GCC 4.8
was used. so let's play safe and use -O2 for now...

reduce the default optimization level from -O3 to -O2

---

opm/core/linalg/LinearSolverPetsc.cpp

This PR fixes two issues:
* Compilation with g++-4.4 because of missing conversion from const char* to char* triggered by converting a pair of const char* to a pair of std::string.
* Missing suppport for KSPCHEBYSHEV in PETSc 3.2
And thus fixes issue #726

Fixex compile issues with PETSc on Debian wheezy

---

opm/core/linalg/LinearSolverPetsc.cpp

This commit updates the source code comment about using operator[] to
initialize the unordered map. Thanks to Bard's persistence we found
out that the cause is not the construction of the key value of type
std::string from const char* but the mapped type being a (mutable)
char* (due to C?).
This completes the PR #784.

Correct documentation of why we use operator[] to initialize map. (Completes #784)

---

examples/compute_eikonal_from_files.cpp
examples/compute_initial_state.cpp
examples/compute_tof.cpp
examples/compute_tof_from_files.cpp
opm/core/utility/parameters/ParameterGroup.cpp
opm/core/utility/parameters/ParameterGroup.hpp
opm/core/utility/parameters/ParameterGroup_impl.hpp
tests/test_param.cpp

The ParameterGroup class will after this no longer ignore command-line arguments it does not handle itself, but store and make the unhandled arguments available through the unhandledArguments() method.
This should not affect existing usage. The reason for the change is a need for more command-line flexibility for applications such as flow.

Store unhandled command-line arguments

---

opm/core/io/eclipse/EclipseWriter.cpp

The ert ecl_sum class is avare of time units; for FIELD and METRIC units
the time in the summary files is stord in days, for LAB units it is
stored in hours. From EclipseWriter this is managed by a bool flag
'time_in_days.
This is merged together with: https://github.com/Ensembles/ert/pull/745
I was originallly intending to wait with this combination; but the ERT PR was requested and it was getting increasingly uncomfrtable maintaining the revert-of-revert branch of ERT updates.

Added bool time_in_days to ecl_sum constructor.

---

opm/core/io/eclipse/EclipseWriteRFTHandler.cpp
opm/core/simulator/SimulatorReport.cpp
opm/core/simulator/SimulatorReport.hpp

This is a little bit of polish to make the output from Flow generate a little less user confusion.
I intend to put this in the release branch as well.

Minor output fixes

---

cmake/Modules/Finddune-istl.cmake

this makes the cmake module usable by downstream modules which do not
explicitly specify an UMFPACK dependency.

Finddune-istl.cmake: Add UMFPACK as an optional dependency

---

opm/core/wells/WellsManager.cpp
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp

In a parallel run each process only knows a part of the grid. Nevertheless
it does hold the complete well information. To resolve this the WellsManager
must be able to handle this case.
With this commit its constructor gets a flag indicating whether this is
a parallel run. If it is, then it does not throw if a well has cells that
are not present on the local part of the grid. Nevertheless it will check
that either all or none of the cells of a well are stored in the local part
of the grid.
Wells with no perforated cells on the local will still be present but set to SHUT.

Adds possibility of having a well not stored on a grid partitioning.

---

opm/core/simulator/SimulatorReport.cpp
opm/core/simulator/SimulatorReport.hpp
opm/core/utility/parameters/Parameter.hpp
opm/core/utility/parameters/ParameterGroup.cpp
opm/core/utility/parameters/ParameterGroup.hpp
opm/core/utility/parameters/ParameterGroup_impl.hpp
opm/core/utility/parameters/ParameterXML.cpp
opm/core/utility/parameters/ParameterXML.hpp

This allows for deactivating output to std:cout. This is handy for parallel runs where we only
want to print statistics on one process.

 Allow to prevent printing to std::cout.

---

README

This minor change:
- updates the list of components (remove deck input, add flow diagnostics),
- updates some deps to no longer be optional,
- warns the user of the need to use synced versions of ERT and OPM.
The last change is in response to #801.
The whole README should be checked for accuracy, especially that the install instructions work on SUSE and Red Hat, but that should not delay the current fix.

Update to notify user of known problem.

---

opm/core/linalg/ParallelIstlInformation.hpp

In this case the parallel index set might represent N entries (this might be the number of
cells of grid). Nevertheless, there are several (n) equations/unknowns attached to each index.
In this case we construct a larger index set representing N*n unknows, where each unknown
is attached to an index.
This change only affects parallel runs.

Allow to create the correct communication information for several unknowns.

---

opm/core/wells/WellsManager.cpp
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp

Previously, we used the setStatus method to set wells that do not
exist on the local grid to SHUT. Or at least this is what I thought
that ```well.setStatus(timestep, SHUT)```. Unfortunately, my
assumption was wrong. This was revealed while testing a parallel run
with SPE9 that threw an expeption about "Elements must be added in
weakly increasing order" in Opm::DynamicState::add(int, T). Seems like
the method name is a bit misleading.
As it turns out the WellManager has its own complete list of active
wells (shut wells are simply left out). Therefore we can use this
behaviour to our advantage: With this commit we not only exclude shut
wells from the list, but also the ones that do not exist on the local
grid. We even get rid of an ugly const_cast.
With this PR I was able to run SPE9 in …

[bugfix,parallel] Deactivate non-existing wells in manager.

---

opm/core/linalg/ParallelIstlInformation.hpp
opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/TimeStepControl.cpp
opm/core/simulator/TimeStepControl.hpp
tests/test_parallelistlinformation.cpp

The only stage where parallelism changes the adaptive time stepping is when some inner products on the saturation andpressure are computed.
This PR makes this part parallel by adding an additonal boost::any parameter to the constuctor of the adaptive time stepping and the controller classes. Per default this is empty. In a parallel run it contains a ParallelIstlInformation object encapsulating the information about the parallelisation. This then used
to compute the parallel inner product.
There will be a small upcoming PR in opm-autodiff that uses this one.

Make adaptive time stepping parallel

---

opm/core/simulator/TimeStepControl.hpp

A function argument is only used in the HAVE_MPI block.

Suppress a warning in serial mode.

---

opm/core/linalg/ParallelIstlInformation.hpp
tests/test_parallelistlinformation.cpp

Bård spotet a bug after PR #805 was merged. Indead returning ```-numeric_limits<type>::min()``` does not make sense for integral values. This commit resorts to returning numeric_limits<type>::min() and adds some more tests.

Fix mask to min (completes PR PR #805)

---

opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/EclipseWriter.hpp
tests/test_EclipseWriter.cpp
tests/test_writenumwells.cpp

Use the IOConfig object from EclipseState to decide:
* Whether restart file should be written for a specified report step
* whether restart files are to be unified or not (UNIFOUT keyword, default if keyword not present is multiple)
* whether an EGRID file should be written (GRIDFILE, NOGGF keywords)
* whether an INIT file should be written (INIT keyword)
* whether the above files should be formatted or not (FMTOUT keyword, default if keyword not present is unformatted)
* Removed former setting for interval writes to disk (from params) 
* Changed a test due to changes in behaviour when using IOConfig (ie if UNIFOUT keyword not set, default is multiple restart files, not unified)

Opm 206 Use IOConfig from EclipseState to decide which Eclipse output files to write (and when)

---

opm/core/utility/platform_dependent/disable_warnings.h

* -Wpragmas 
This is used to suppress the warnings [-Wpragmas] when the compilers do not recognize the warning options. like 
```
opm-core/opm/core/utility/platform_dependent/disable_warnings.h:59:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
#pragma GCC diagnostic ignored "-Wdeprecated-register"
```
* -Wunused-but-set-variable
This is used to suppress the warnings for unused but set variables.

Adding two more warnings to disable_warnings.h.

---

opm/core/props/satfunc/SatFuncMultiplexer.hpp

"old" == "gcc 4.4". the standard c++ library of this compiler seems to
invoke the copy operator when creating objects in a vector, whereas
newer versions of the library don't. The problem is that std::unique
pointer cannot be copied because it is -- err -- unique and thus the
implicit copy operator for the SatFuncMultiplexer class gets deleted
by the compiler.
the fix is to introduce a "fake" copy operator which does not do
anything but is present to make std::vector of stdlibc++-4.4
happy. this is obviously not very elegant, but I could not come up
with a better solution. (another fix would be to use raw pointers
instead of std::unique_ptr, but IMO this does not qualify as
"better".)

fix SatFuncMultiplexer on old compilers

---

opm/core/simulator/BlackoilState.cpp
opm/core/simulator/BlackoilState.hpp
opm/core/simulator/SimulatorState.cpp
opm/core/simulator/SimulatorState.hpp

This PR changes the implementation of the SimulatorState and BlackoilState such that all derived classes can add data via the registerCellData or registerFaceData. 
Application to simulator data such as I/O or communication can then be implemented on top of the SimulatorState class only. 
The current behavior of both classes should be as before.

Revise SimulatorState and BlackoilState.

---

tests/test_stoppedwells.cpp

This fixes a test failure after the merging of #825.

Do not use pressure() until after init() in BlackoilState.

---

tests/test_ug.cpp

See https://github.com/OPM/opm-parser/pull/525 and #830 for context.
This is a pure unittest - which I think should be merged. Observe that the code which is actually tested is in opm-parser. With current opm-parser the new test fails - but with https://github.com/OPM/opm-parser/pull/526 applied the test will pass.

Unittest creating UnstructuredGrid with TOPS.

---

opm/core/linalg/call_umfpack.c

The UF_long type is deprecated in UMFPack, and actually seems to be removed from the latest versions.
In the long term, we should switch to using SuiteSparse_long instead of UF_long, but that would increase the minimum version required to 4.0.0 (I think). The proposed solution defines a macro only in the .c file where it is used.

Define the UF_long type if necessary.

---

opm/core/props/satfunc/SatFuncBase.hpp

this caused the hysteresis saturation shifts to be initially wrong and
was probably the source of a lot of my confusion w.r.t. the saturation
scaling and hysteresis shift code. I guess this also fixes a valgrind
complaint, but I haven't checked...
I propose this PR as a precursor to #834 because it makes the comparison stuff easier because it fixes a bug in the current code.

properly initialize the attributes of the SatHyst class

---

opm/core/io/eclipse/EclipseWriter.cpp
opm/core/simulator/AdaptiveSimulatorTimer.cpp
opm/core/simulator/AdaptiveSimulatorTimer.hpp
opm/core/simulator/SimulatorTimerInterface.hpp

No need for to use new methods startOfCurrentStepPosixTime() / currentStepStartTime() / simmulationStartTimeForCurrentReportStep() when substep data are not written to restart file. Removing the method and use of it.

Reverse changes that should not have been merged into master

---

opm/core/flowdiagnostics/AnisotropicEikonal.hpp
opm/core/grid/GridUtilities.cpp
opm/core/grid/grid.c
opm/core/linalg/ParallelIstlInformation.hpp
tests/DuneIstlTestHelpers.hpp
tests/test_anisotropiceikonal.cpp
tests/test_parallel_linearsolver.cpp
tests/test_parallelistlinformation.cpp
tests/test_regionmapping.cpp
tests/test_shadow.cpp
tests/test_sparsetable.cpp

This fixes a bug in an internal utility that affected the grid_equal() function (it would give false positives).
Also, many warnings have been silenced. (The bug was discovered during the warning-squashing process as a compiler warning was given for the buggy behaviour.)

Fix abs bug and warnings

---

opm/core/props/satfunc/SaturationPropsFromDeck_impl.hpp
opm/core/simulator/ExplicitArraysFluidState.hpp

This makes the two-phase simulators work again. It could have a negative effect on #834, if that requires the number of phases to be known at compile time. If so, we need to discuss how to work that out.

Fix bugs related to ExplicitArraysFluidState

---

opm/core/wells/WellsGroup.cpp
tests/test_wellsgroup.cpp

Production controls now are no longer initialised from injection control data.
This requires OPM/opm-parser#554.

Use the correct (new) method from the Group class for group RESV.

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

This can be thrown by the ILU0 preconditioner when using the interleaved solver approach. Catching it allows us to shorten timesteps etc. as we do with other kinds of linear solver trouble.
This makes it possible to run through Norne with the interleaved solver.

Catch more istl exceptions

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp

To set its value to be `true`, the grammar is `full_timestep_initially=true`. 
When the option is true, for each report step, the size of the adaptive time step always beginning with the size of the report step.
The implementation of the current master branch is to use the average time step from the running of the previous report step. Under some conditions, it can result in relative small time step for the subsequent report steps. 
A preliminary test with all the other options defaulted, `full_timestep_initially_=true` reduce the number of Newton iterations from 2585 (current master branch with dune2.3) to 2143. And total running time from 5504 seconds to 4867 seconds. 
Before we decide to make this option to be `true` by default, it is `false` by default at the moment.

adding command line option full_timestep_initially_

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

In a constructor initialisation list, the order should be the same as the order in which the variables actually are initialised, which is given by the order they are declared in the class and not by the order in the initialisation list.

Match init order to member order.

---

examples/compute_tof.cpp
opm/core/pressure/tpfa/cfs_tpfa_residual.c
opm/core/pressure/tpfa/ifs_tpfa.c
opm/core/simulator/WellState.hpp
opm/core/well_controls.h
opm/core/wells.h
opm/core/wells/WellsGroup.cpp
opm/core/wells/WellsManager.cpp
opm/core/wells/well_controls.c
opm/core/wells/wells.c
tests/test_wellcontrols.cpp
tests/test_wells.cpp

This sets up for using vertical flow performace tables for production and injection wells (i.e., tubing head pressure control). 
Most of the actual VFP code resides in opm-autodiff, but this should compile and run without merging that first.

Vertical flow performance tables

---

CMakeLists_files.cmake
opm/core/io/eclipse/EclipseIOUtil.hpp
opm/core/io/eclipse/EclipseReader.cpp
opm/core/io/eclipse/EclipseReader.hpp
tests/test_readWriteWellStateData.cpp

Extended EclipseReader with read of temperature, pressure, sgas and swat from restart file. 
Added unit test.
This code is not in use yet, it will be when Flow supports restarts. 
This PR is not dependent upon other PRs.

Opm 215 EclipseReader restart file read of solution data

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp

The last estimated time-step is used for the initial sub-step in the report step instead of the average of the time-steps used in the previous report step.
. 
Testes: 
Norne: 3.7% speedup
SPE1: (run using: flow SPE1DECK.DATA): 37% speedup
SPE9: (run using: flow SPE9.DATA) 15% speedup.

Use estimated time-step instead of average in next report step

---

opm/core/grid/MinpvProcessor.hpp

Model 2 partly uses PORO=0.0 to signal inactive cells. This PR
prevents such cells from causing unwanted zcorn modifications in
the current min-pv algoritm. (The problem is however more general as
zero PORO or NTG should kill a cell whether MINPV is active or not,
refer kw ACTNUM.)

Zero-porosity cells and MINPV.

---

opm/core/simulator/AdaptiveSimulatorTimer.cpp

Previously there was an assertion whether the time stepping is still
running when querying the time step. After commit 5af794cfd588b this
triggered an assertion for Norne. As there is no reason to limit querying
the current time step in this way. This commit simply removes the assertion
in AdaptiveSimulatorTimer::currentStepLength.
This closes OPM/opm-autodiff#446

[bugfix] Allow querying the current time step even if we are done.

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/TimeStepControl.cpp
opm/core/simulator/TimeStepControl.hpp

The time step restriction is moved to AdaptiveTimeStepping_impl.hpp to
make it apply to all time-stepping algorithms.

Limit the time step growth for all time-stepping algorithm

---

opm/core/utility/memcmp_double.c
opm/core/wells/well_controls.c
opm/core/wells/wells.c

gcc-4.7.2 (Debian 4.7.2-5) complained about:
```
'for’ loop initial declarations are only allowed in C99 mode
note: use option -std=c99 or -std=gnu99 to compile your code"
```
when seeing somethink like this:
```c
for(int i=0; i<end; i++)
```
This is fixed by moving the declaration before the for loop with
this commit. Altenatively, we could use the above option.

Fix complaint about initial declaration in foor loops.

---

opm/core/wells/WellsManager_impl.hpp

Previously well with just some shut completions erroneously triggered an exception in parallel runs. This is fixed with this commit.
Due to the logic shut completions will always be marked as existing on a process. (Initially all  completions are marked as found. For each open completion we check whether the Cartesian index belongs to the local grid. If that is not the case we mark it as not found). Therefore we now check whether the found number of completions is either the number of shut completions or the number of all completions. In the former case the well is not stored on this process, and in the latter case it is. In other cases we throw an exception.

[bugfix] Account for shut completions when checking well in parallel

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

- use time stepping algorithm pid instead of pid + iter
Adjusting the time-steps on the number of linear iterations does
currently not give any improvents on the time-stepping.
- Change the pid tolerance. The time-stepper will take longer time-steps
and thus reduce the simulation time significantly. The Norne and the SPE
results does not degrade
- Less aggressive reduction of time-steps after convergence problems

Change default values

---

opm/core/wells/WellsManager_impl.hpp

If on one process a well completion is next to border then
it might also be stored in the neighbor process. Still not
all the completions of the well are known to the neighbor.
This breaks the previous assumption that for each well all
completions must belong to the partition of the process.
Therefore with this commit we allow wells that only have a
part of their completions assigned to the partition of the process.
This wells are deactivated under the assumption that they must
exist completely on another process due to the partitioning.

Allow a few well completions in the overlap.

---

opm/core/grid/GridHelpers.cpp
opm/core/grid/GridHelpers.hpp

There is a sligth difference between the cell depth taken from the
centroid (opm) and a straightforward average of corner coordinates
(ecl). For the initialisation of Norne this causes some differences
when deciding cell center positions relative contact depths.

Cell center depth also from zcorn average.

---

opm/core/props/BlackoilPropertiesFromDeck_impl.hpp
opm/core/props/IncompPropertiesFromDeck.cpp
opm/core/simulator/SimulatorState.hpp
opm/core/simulator/initState_impl.hpp

This PR adds methods numCells and numFaces to SimulatorState and also allows to register data from outside. This is needed for the ParallelOutput. 
Also, some warnings in BlackoilPropsFromDeck have been fixed.

SimulatorState: export num_cells_ and num_faces_.

---

opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp

The `dz` calculated in `WellDetails::getCubeDim()` is not correct in cases where the face centroid of the horizontal faces is located above or below the face centroid or the vertical faces. The cell thickness in EclipseGrid, calculated using the Z-coordinates, is therefore used instead.
Tested on SPE9 with corner-point geometry. 
Questions to the reviewers.
1. Should the call to `WellDetails::getCubeDim()` be moved outside `createWellsFromSpecs` and instead the cell dimensions passed directly.
2. Do we need to calculate `dx` and `dy` from the z-coordinates as well?

Use cell thickness from EclipseGrid in the well transsmissibility

---

CMakeLists_files.cmake
opm/core/props/BlackoilPropertiesFromDeck.cpp
opm/core/utility/compressedToCartesian.cpp
opm/core/utility/compressedToCartesian.hpp
opm/core/wells/WellsManager_impl.hpp

The `compressedToCartesian()` function has been moved to a separate header and used to avoid error in the case a `nullptr` is passed for `global_cell` in `WellsManager`.
I expect that this very minor utility can be useful a few other places as well.

Account for possible null global_cell

---

opm/core/simulator/EquilibrationHelpers.hpp
opm/core/simulator/initStateEquil.hpp
opm/core/simulator/initStateEquil_impl.hpp
opm/core/utility/RegionMapping.hpp
tests/test_equil.cpp
tests/test_regionmapping.cpp

This change-set addresses the issue that was brought up in PR #858.  We introduce support for arbitrary region lookup provided the region ID supports `std::hash<>` and simplify the interface by replacing the custom `CellRange` class with a `boost::iterator_range<>`.
Method `cells()` returns an empty range if the region ID corresponds to an inactive region.
Note: The changes to `EquilibrationHelpers.hpp` and `initStateEquil_impl.hpp` are, strictly speaking, ancillary, but the issues were highlighted by this work and the changes included for convenience.
Note: This supersedes and closes #864.

RegionMapping<>: Support arbitrary active regions

---

opm/core/simulator/WellState.hpp

This PR moves the wellname -> wellIndex mapping from WellStateFullyImplicitBlackoil to the base class. 
This is needed for the ParallelDebugOutput where we only have WellSate objects and need this mapping (which is already available in the Blackoil stuff).

WellState: move mapping from well name to well index to here.

---

opm/core/wells/WellsManager_impl.hpp

While hopefully not a bug it raises an exception with gcc's
libc debugging mode. Therefore we resort to using C++11's
std::vector::data instead.
The exception was raised when running SPE9 in parallel.

Prevent WellsManager from subscripting empty container.

---

opm/core/io/eclipse/EclipseWriter.cpp

Avoid division on time in the total output of rates.

Use correct units for the accumulated output

---

opm/core/wells/WellsManager_impl.hpp

Completions that are not found in the grid are ignored. 
This is a necessary fix to make Model 2 run.

WARN instead of THROW if completion is not found in the grid

---

opm/core/props/pvt/PvtDead.cpp
opm/core/props/pvt/PvtDead.hpp
opm/core/props/pvt/PvtDeadSpline.cpp
opm/core/props/pvt/PvtDeadSpline.hpp
opm/core/props/pvt/ThermalGasPvtWrapper.hpp
opm/core/props/pvt/ThermalOilPvtWrapper.hpp
opm/core/props/pvt/ThermalWaterPvtWrapper.hpp
opm/core/props/rock/RockCompressibility.cpp
opm/core/simulator/initStateEquil.hpp

Followup to: https://github.com/OPM/opm-parser/pull/585
Comments are welcome - but this should *not* be merged before the opm-parser PR is merged.
With this PR the `DeckWithLiveOil` test in `test_equil.cpp` fails. To me it seems that the test should have failed all along, but that out of bounds access to the previous `std::vector<RsvdTable>` implementation failed silently?

Changed Table code to use TableContainer

---

CMakeLists_files.cmake
opm/core/grid/grid.c
opm/core/utility/opm_memcmp_double.c
opm/core/utility/opm_memcmp_double.h
tests/test_ug.cpp

The prefix `mem` is supposedly reserved for standard functions.

Renamed memcmp_double -> opm_memcmp_double

---

opm/core/wells.h
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp
opm/core/wells/wells.c
tests/test_wells.cpp
tutorials/tutorial4.cpp

This PR adds allow_cf to the wells structure that determine whether
crossflow is allowed or not. An extra argument is added to addWell(..)
to specify the allow_cf flag.
Should be considered together with OPM/opm-parser#600
@bska I would appreciate if you could take a look at this. I still feel shaky whenever I touching the wells in opm-core.

Add boolean flag to determine whether crossflow is allowed in a well

---

opm/core/grid/PinchProcessor.hpp
tests/test_pinchprocessor.cpp

This silences warnings. It also makes it clear that
the cell thicknesses are not used in the current
algorithm, the doc comment has been updated to
reflect this.

Remove unused arguments in PinchProcessor methods.

---

opm/core/io/eclipse/EclipseWriteRFTHandler.cpp
opm/core/io/eclipse/EclipseWriter.cpp

The currentStepNum() method was used (wrongly) instead of reportStepNum() in the RFT-related parts of EclipseWriter and in EclipseWriteRFTHandler.
Also improved formatting in that part of the EclipseWriter (separate commit).
@joakim-hove I have assigned you to review/merge this.

Fix timestep bug

---

opm/core/simulator/EquilibrationHelpers.hpp

Backports parts of a7b1e69a45c14ec88a82b92ee704424f1ea1b41c
This breaks 'test_equil' on other archs as round-off causes the different branch to be taken, thus altering application behavior significantly.

fix Equilibration test by adding some fuzz

---

opm/core/linalg/ParallelIstlInformation.hpp

Previously, we copied owner/overlap to all which is clearly wrong.
Now we copy from owner to all as the function name says.
As this is a bugfix and it would make sense to include it in the release.

[bugfix] Fixes copyOwnerToAll.

---

opm/core/props/rock/RockFromDeck.cpp
opm/core/props/rock/RockFromDeck.hpp

This is needed in parallel runs where a the rock properties will not
be read from the deck but be communicated from a master process. Nevertheless
we need to be able to initialize the data structures with the correct
container size. In addition we need to be able to change the container values
from opm-autodiff's BlackoilPropsDataHandle.

Allow the rock properties to be zero initialized without a deck.

---

opm/core/wells/WellsManager_impl.hpp

In the parallel run there are cases where wells perforate cells
that are neighbors of overlap/halo cells. On other process only
parts of the well are seen as perforations. These wells should be
ignored there. While the well was indeed ignored, the perforations
found where mistakenly added to the well found due not clearing the
wellperf_data[well_index]. This commit now does this clearing and
results in the right handling of wells for e.g. SPE9.

Fixes well manager for wells crossing into cells that overlap.

---

opm/core/simulator/initStateEquil_impl.hpp

The number is changed from 100->2000 to increase accuracy.
According to @osae this is necessary to get match for the new model. 
An alternative fix that would require less integration points would be to compute the span of the integration pr. pillar instead and to make the number of integration points dependent on the size of the integration span.

Change the number of integration points in the initialization

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/TimeStepControl.cpp
opm/core/simulator/TimeStepControl.hpp
opm/core/simulator/TimeStepControlInterface.hpp

This PR revises the TimeStepControl interface such that the computation of the 
error || u^n+ - u^n || / || u^n+1 || is forwarded to the Model class. This allows for more flexible and model dependent implementation. A corresponding PR in opm-autodiff is coming.

AdaptiveTimeStepping: allow for more flexible error computation in the future.

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

With this, opm-autodiff builds again.
Will self-merge, as it is a small fix for a build-failure.

Follow class renaming.

---

opm/core/linalg/ParallelIstlInformation.hpp

Thus we can actually access the mask in external code. This is for
example needed when calculating averages in RateConverter of opm-autodiff.

Return a constant reference to the mask for ParallelISTLInformation::updateOwnerMask

---

opm/core/props/BlackoilPropertiesFromDeck.hpp
opm/core/props/pvt/BlackoilPvtProperties.hpp
opm/core/utility/thresholdPressures.hpp

This needs to be done if a equilibration region transition is
mentioned by the THPRES keyword, but no value is given for this record
in the third item. (it seems that this is used quite frequently.)
Also, the approach taken by this patch also does not collide with the
restart machinery as far as I can see. This is because the initial
condition is applied by the simulator before the state at the restart
time is loaded. (I interpreted the code that way, but I could be
wrong, could anyone verify this?)
since it is pretty elaborate to calculate initial condition, this
patch is pretty messy. I also do not know if Eclipse does include
capillary pressure in this calculation or not (this patch does) and
there may be other bugs lurking. happy testing!

implement determining the threshold pressure from the initial condition

---

opm/core/simulator/initStateEquil_impl.hpp

CellCenterDepth is used instead of z coordinate of the cell centroid. The cellCenterDepth is calculated based on the cell corners as Eclipse.

Use cell depths based on averaging cell corners

---

tests/DuneIstlTestHelpers.hpp

my boost is 1.58. once more, boost seemed to have become more picky on
where a semicolon must be placed and where not.

fix build for newish boost versions

---

opm/core/grid/GridHelpers.hpp
opm/core/utility/thresholdPressures.hpp

The thresholdPressures() should probably be changed to not take a deck, but that requires cross-module changes so I'll not do it here.
I consider this trivial enough to self-merge.

Silence some warnings.

---

opm/core/grid/GridManager.cpp
opm/core/grid/MinpvProcessor.hpp
opm/core/grid/PinchProcessor.hpp
opm/core/utility/thresholdPressures.hpp
tests/test_minpvprocessor.cpp
tests/test_pinchprocessor.cpp

- adding of the removed pore volume to the above cell is made optional.
- changes is made in the PinchProcessor to account for the change in the MinpvProcessor.
- a method that return the thressholdpressures for the NNCs are added
Note this is not compatible with #907

compatibility of MINPV and PINCH  

---

opm/core/props/BlackoilPropertiesFromDeck.cpp
opm/core/props/pvt/PvtInterface.cpp
opm/core/props/pvt/PvtInterface.hpp

Minor refactor - use EclipseState instead of Deck for PvtInterface. 
If PVTNUM is not present, getIntGridProperty() returns a vector with pvtnum 1 for each gridcell/box. 
Due to changes in extractPvtTableIndex() method signature, the PR https://github.com/OPM/opm-autodiff/pull/569 should be merged at the same time.

OPM-163: Use EclipseState instead of Deck for PvtInterface

---

CMakeLists_files.cmake
opm/core/io/eclipse/EclipseReader.cpp
opm/core/io/eclipse/EclipseReader.hpp
opm/core/io/eclipse/EclipseWriter.cpp
opm/core/io/eclipse/EclipseWriter.hpp
opm/core/simulator/SimulatorTimer.cpp
opm/core/simulator/SimulatorTimer.hpp
tests/test_writeReadRestartFile.cpp

This PR is ready for review / merging. 
Added the following to support restart of flow from a restart file (written by flow):
- Extended EclipseReader with methods to init WellStateObject and SimulatorState from restart file. 
- Extended EclipseWriter with RV and RS data
- Extended test for the above read/write
- Added date for restart file
- Change in SimulatorTimer: jump to restart time
MPI is not taken into account

OPM-251: Prepare for restart

---

opm/core/simulator/SimulatorState.cpp
opm/core/simulator/SimulatorState.hpp
tutorials/tutorial3.cpp
tutorials/tutorial4.cpp

When this overload has been removed the `SimulatorState` class has no dependencies to other parts of opm-core, and it can be moved to opm-common.
The overload seemed to be only used in the tutorials.

Removed SimulatorState::init( UnstructureGrid& )

---

opm/core/props/pvt/PvtLiveGas.cpp

at least, don't special case that much: the  condition seems fishy to me because it only applies for the fist PVT region (i.e., `is == 0`), and the generic code below the if works just fine as well.
This caused a discrepancy with the opm-material PVT relations for Norne after 23 report steps. (which takes an hour or two to get to with debugging options on my machine.) As you can probably imagine, finding this was *a lot* of fun...

PvtLiveGas: do not special case in the extrapolation code

---

examples/mirror_grid.cpp
opm/core/grid/GridManager.cpp
opm/core/io/eclipse/CornerpointChopper.hpp
opm/core/io/eclipse/EclipseGridInspector.cpp
opm/core/io/eclipse/EclipseReader.cpp
opm/core/io/eclipse/EclipseWriter.cpp
opm/core/props/IncompPropertiesSinglePhase.cpp
opm/core/props/pvt/BlackoilPvtProperties.cpp
opm/core/props/pvt/PvtConstCompr.hpp
opm/core/props/pvt/PvtPropertiesIncompFromDeck.cpp
opm/core/props/pvt/ThermalGasPvtWrapper.hpp
opm/core/props/pvt/ThermalOilPvtWrapper.hpp
opm/core/props/pvt/ThermalWaterPvtWrapper.hpp
opm/core/props/rock/RockCompressibility.cpp
opm/core/props/satfunc/RelpermDiagnostics.cpp
opm/core/simulator/initState_impl.hpp
opm/core/utility/thresholdPressures.hpp
tests/test_EclipseWriter.cpp
tests/test_parser.cpp
tests/test_ug.cpp

OPM/opm-parser#677 changes the return types for the Deck family of classes.
This patch fixes all broken code from that patch set.
https://github.com/OPM/opm-parser/pull/677

Change Deck access methods/types to references

---

opm/core/utility/CompressedPropertyAccess.hpp
opm/core/utility/thresholdPressures.hpp

it broke because EclipseState::get*GridProperty() now returns a
pointer to a constant object.
this patch us thus required as a follow-up of OPM/opm-parser#687

fix the build

---

opm/core/pressure/IncompTpfa.cpp
opm/core/pressure/IncompTpfa.hpp
opm/core/simulator/BlackoilState.cpp
opm/core/simulator/BlackoilState.hpp
opm/core/simulator/SimulatorState.cpp
opm/core/simulator/SimulatorState.hpp
opm/core/simulator/TwophaseState.hpp
opm/core/simulator/TwophaseState_impl.hpp
opm/core/simulator/initState.hpp
opm/core/simulator/initState_impl.hpp
tutorials/tutorial3.cpp
tutorials/tutorial4.cpp

Have removed the `setFirstSat()` method, which had a dependency on `template <class Props>` and instead moved the property lookup to the `initState_impl.hpp` file. The initialisation of saturations is now based on a genereric `SimulatorState::setCellDataComponent()` function.
This is not necessarily a perfect API - but with this in place it should be possible to use the `SimulationDataContainer` from opm-common as drop in replacement for `SimulatorState`.
Currently this PR and: https://github.com/OPM/opm-common/pull/76 can be merged independently.

Changes in SimulatorState:

---

opm/core/props/satfunc/RelpermDiagnostics.hpp
opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
tests/test_relpermdiagnostics.cpp

This fixes a few issues resulting from the change to make two of the methods templates.

Fix minor issues with RelpermDiagnostics

---

opm/core/simulator/SimulatorTimer.cpp
opm/core/simulator/SimulatorTimer.hpp

Requires follow-up PR in opm-autodiff.

Remove unused 'restart' parameter from SimulatorTimer::init().

---

opm/core/simulator/EquilibrationHelpers.hpp
opm/core/simulator/initStateEquil.hpp
opm/core/simulator/initStateEquil_impl.hpp
opm/core/simulator/initState_impl.hpp
tests/test_equil.cpp

Upstream (opm-parser) now provides a better Equil + EquilRecord, and simultaneously deprecated EquilWrapper. This patch fixes the resulting breakage.
One important note: The new Equil does not expose integers for live oil/wet gas initialization procedure methods, but rather Booleans through `constRs`/`constRv` methods. This is how the variable behaves
according to the Eclipse reference manual (`EQUIL` keyword section)
Code has been updated to reflect this.
This PR is replacing and closes #960
Upstream PR is OPM/opm-parser#698

Remove Equil + EquilWrapper, replace with upstream

---

opm/core/io/eclipse/EclipseWriter.cpp

this *might* fix the PERM[XYZ] fields in the ECL restart files. notice the emphasis on the *might*: this is because I could not properly test the patch because ResInsight seems to have issues with the restart file produced by `flow`. (I haven't found a way to make it display the PERM[XYZ] fields. I have tested that this is the case for both this PR's branch as well as well as the current opm-core and opm-autodiff master versions.) So:
Before you merge this, please test carefully
==

Fix PERM[XYZ] output

---

opm/core/props/satfunc/RelpermDiagnostics.hpp

OpmLog has been moved from parser to common in these two PRs:
https://github.com/OPM/opm-common/pull/90/files
https://github.com/OPM/opm-parser/pull/721
Changed include due to this

Changed include due to OpmLog changed path

---

opm/core/simulator/AdaptiveSimulatorTimer.cpp
opm/core/simulator/AdaptiveSimulatorTimer.hpp
opm/core/simulator/SimulatorTimer.cpp
opm/core/simulator/SimulatorTimer.hpp
opm/core/simulator/SimulatorTimerInterface.hpp

Since we are dealing with a virtual interface here we needed to add a method clone that creates a copy of the real object. This is needed in an upcoming PR in opm-autodiff.

Allow SimulatorTimers to be copied.

---

opm/core/wells/WellsManager_impl.hpp

With this fix guide rates for group control can be specified correctly using WRUPCON

BUGFIX. Call setupGuideRates before groupcontrol is applied

---

opm/core/pressure/tpfa/TransTpfa_impl.hpp

Rename HAVE_DUNE_CORNERPOINT -> HAVE_OPM_GRID. 
Note that this is a little strange since opm-core is upstream and not downstream
from opm-grid. However, when this file is used from opm-autodiff the macro is required.
Requires OPM/opm-common#104.

Module renaming

---

opm/core/wells/WellCollection.cpp
opm/core/wells/WellsManager.cpp
tests/wells_group.data

- Handle shut wells
- Use the groups control type to determine which phase to calculate
the guide rates from. i.e for a ORAT controlled group, calculate the
guide rates from the oil phase well potentials etc.

Bugfix in setup guiderates

---

examples/compute_initial_state.cpp
examples/compute_tof.cpp
examples/diagnose_relperm.cpp
examples/wells_example.cpp
opm/core/grid/GridManager.cpp
opm/core/grid/GridManager.hpp
opm/core/wells/WellsManager_impl.hpp
tests/test_EclipseWriteRFTHandler.cpp
tests/test_EclipseWriter.cpp
tests/test_blackoilstate.cpp
tests/test_column_extract.cpp
tests/test_compressedpropertyaccess.cpp
tests/test_pinchprocessor.cpp
tests/test_relpermdiagnostics.cpp
tests/test_stoppedwells.cpp
tests/test_ug.cpp
tests/test_wellsmanager.cpp
tests/test_writeReadRestartFile.cpp
tests/test_writenumwells.cpp

This PR adds two fixes
* First, now we are using the new EclipseState.getInputGrid API in Parser
* Second, this PR fixes a bug introduced in ACTNUM PR OPM/opm-parser#768 (see issue #1001)
* Third, fixes arbitrary indentation in test file
See OPM/opm-parser#769

 Using getInputGrid API from Parser

---

opm/core/props/BlackoilPropertiesFromDeck.cpp
opm/core/props/phaseUsageFromDeck.hpp
opm/core/simulator/initState_impl.hpp

This PR enables running a two phase test case with plausible results
This PR should have no side effects for running existing three phase simulations. See also the twin PR in opm-simulators which should be merged simultaneously with this one

Two phase bugfixes

---

jenkins/build-opm-core.sh
jenkins/build-pr.sh
jenkins/build.sh

use 'jenkins build this with downstreams please'.
this will build all downstreams against the PR, and
execute their tests. PR's for upstream and downstream modules
can be specified.
the aggregated test results are attached to the job result on jenkins.
depends on https://github.com/OPM/opm-common/pull/111

added: downstream build support in the jenkins trigger

---

opm/core/simulator/initStateEquil.hpp

This happened for empty regions and surfaced when compiling
with "-D_GLIBCXX_DEBUG  -DDEBUG -DGLIBCXX_FORCE_NEW".
This closes #1008, but I am not sure whether pushing nullpointers to rs_func_ and rv_func_ is a good idea.

Prevent dereferencing the end iterator.

---

CMakeLists_files.cmake
opm/core/simulator/BlackoilState.cpp
opm/core/simulator/BlackoilState.hpp
opm/core/utility/initHydroCarbonState.hpp

The hydroCarbonState is used to store the hydroCarbonState
State 1: Gas only
State 2: Gas and Oil
State 3: Oil only
An empty vector is return at initialization as
no default values are provided by the blackoilstate.

Add member hydroCarbonState to the BlackoilState

---

examples/diagnose_relperm.cpp
opm/core/props/satfunc/RelpermDiagnostics.cpp
opm/core/props/satfunc/RelpermDiagnostics.hpp
opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
tests/test_relpermdiagnostics.cpp

With https://github.com/OPM/opm-common/pull/115, the diagnostics messages will not output prefix twice.

Unify output messages format.

---

examples/compute_initial_state.cpp
examples/compute_tof.cpp
examples/compute_tof_from_files.cpp

On my system I got
```c++
error: variable ‘std::ofstream file’ has initializer but incomplete type
std::ofstream file(fname.str().c_str());
```
This is fixed with this commit by including fstream. Previously, this include might have happened implicitely.

Fix incomplete type error for std::ofstream in examples

---

opm/core/utility/parameters/ParameterGroup_impl.hpp

These parameters notification actually are not very useful for user, we should let these information go into Debug.

paramemters output should go in Debug mode.

---

opm/core/utility/initHydroCarbonState.hpp

- adds boolean has_disgas and has_vapoil to initHydroCarbonState()

Fix to handle cases without DISGAS and VAPOIL

---

opm/core/props/BlackoilPropertiesFromDeck.cpp

this was an involuntary omission in the "local AD" to "dense AD" rename...
I'm open to change this to a better suffix, so feel free to suggest one in the comments. It should probably be noted that this PR is self contained, but for consistency reasons it would be beneficial to merge it together with its opm-simulators counterpart (OPM/opm-simulators#706).

rename some variables from "Lad" to "Eval" (was: to "Dad")

---

opm/core/linalg/LinearSolverFactory.cpp

Check for the right preprocessor define to enable umfpack support.
Matches the directive set in `config.h`
I'm not completely sure if this indicates that my system is broken or if it's something that got lost in a change some time ago, but the umfpack test would fail on recent checkouts.

Check for HAVE_UMFPACK in LinearSolverFactory

---

opm/core/linalg/ParallelIstlInformation.hpp

This is needed in opm-simulator to calculate the parallel euclidian product of the saturations.

Make ParallelIstlInformation::ownerMask_ accessible.

---

opm/core/props/BlackoilPhases.hpp

This makes it simpler to write code debugging or inspecting changed phase configurations.

Add operator== and operator!= to PhasePresence.

---

dune.module

without it, building with dunecontrol fails. (for me.)

add opm-output as a dependency to dune.module

---

opm/core/linalg/ParallelIstlInformation.hpp
tests/test_parallelistlinformation.cpp

In #1026 a `MaxAbs` reduction was added. It causes ambiguous calls for me, when trying to instantiate `std::abs(x)` with x and unsigned integer type.
The suggested patch avoids this by adding a specialization for `std::size_t` in the reduction code, and by using the operator directly in the test.

Avoid ambiguous calls to abs with unsigned integers.

---

opm/core/wells/WellCollection.cpp
opm/core/wells/WellCollection.hpp
opm/core/wells/WellsGroup.cpp
opm/core/wells/WellsGroup.hpp
opm/core/wells/WellsManager.cpp
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp
tests/test_wellcollection.cpp
tests/test_wellsgroup.cpp

shared_ptr aliases are considered deprecated and has largely been
removed upstream (and replaced by raw pointers).
Upstream: https://github.com/OPM/opm-parser/pull/849

WellPtr and GroupPtr deprecated

---

opm/core/wells/InjectionSpecification.cpp
opm/core/wells/ProductionSpecification.cpp

Added six `throw`s (that will never be reached), thereby removing warnings
* OPM-core had 6 warnings (control reaches end of non-void function [-Wreturn-type])
* Removed warnings by adding `throw std::domain_error` that will never be reached
* Added copyright headers for `InjectionSpecification.cpp` and `ProductionSpecification.cpp`

Remove warnings (by throwing), added copyright header

---

opm/core/props/satfunc/SaturationPropsFromDeck.cpp
opm/core/simulator/initStateEquil_impl.hpp

- add guards against non-existing phase
- shift the capillary pressure values with the oil capillary pressure value to handle cases where oil is not the reference case in opm-material. i.e oil-water problems.   
Tested on the Brugge case. Tested that it does not effect norne, Model 2 and SPE9 initialization. 
Not tested on oil-gas problems.

Fix two phase equil initialization

---

opm/core/wells/wells.c

This is needed to run test cases without wells with debugging on.
Without this commit we get a segmentation fault in an assert statement which compares to null well pointers.

Make wells_equal work for null wells.

---

opm/core/props/rock/RockCompressibility.cpp

this is a relatively minor SNAFU over which I stumbled when trying to compare the Jacobian matrices produced by ebos with the ones from flow. I only ran SPE1 and SPE9 on it but did not run Norne. (I did not notice any significant difference for those.)
since
f(x) = 1 + g(x) + 0.5*g(x)*g(x)
the derivative is
f'(x) = 0 - g'(x) + 2*0.5*g(x) * g'(x) = g'(x) + g(x)*g'(x)
note that the previous incorrect values do not affect the quality of
the obtained results (if the tolerance of the non-linear solver is
chosen to be small enough), but it may have deteriorated convergence
rates.

fix incorrect derivative  of rock compressibility w.r.t. pressure

---

examples/compute_initial_state.cpp
examples/compute_tof.cpp
examples/diagnose_relperm.cpp
examples/wells_example.cpp
opm/core/simulator/initStateEquil.hpp
tests/test_blackoilstate.cpp
tests/test_compressedpropertyaccess.cpp
tests/test_equil.cpp
tests/test_norne_pvt.cpp
tests/test_pinchprocessor.cpp
tests/test_relpermdiagnostics.cpp
tests/test_satfunc.cpp
tests/test_stoppedwells.cpp
tests/test_ug.cpp
tests/test_wellcollection.cpp
tests/test_wellsgroup.cpp
tests/test_wellsmanager.cpp

Three minor changes:
* TransMult and InitConfig are returned from parser as references, not shared_ptr
* Use the correct EclipseState constructor, the other will be deprecated.
Downstream of OPM/opm-parser#890.

TransMult and InitConfig are references

---

opm/core/props/satfunc/RelpermDiagnostics.cpp
opm/core/props/satfunc/RelpermDiagnostics.hpp

Number of misc tables is given by NTMISC (MISCNUM) and not NTSFUN
(SATNUM)
Tested on Model 2 with the solvent option.

Bugfix: Let NTMISC determine number of MISC tables

---

opm/core/simulator/WellState.hpp

Used by OPM/opm-simulators#833 to output correct phases.

Pass PhaseUsage to WellState::report

---

opm/core/simulator/WellState.hpp

For these wells access its well_cells might read over the bounds
an array if they are the last wells in the struct. Therefore
we cannot initialize first_cell and the well control is uninitialized,
to.
With this commit theses wells are now detected and the bhp, thp, and well_rates
are initialized to zero.

Zero initialize wells with no perforations.

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/TimeStepControl.cpp
opm/core/simulator/TimeStepControl.hpp
opm/core/simulator/TimeStepControlInterface.hpp

A new timestepper that reads timesteps from "timesteps" generated using
ecl_summary "DECK" TIME > timesteps
and applies it to the simulator
Also a parameter timestep.initial_step_length (default 1 day) is added
to controll the frist timestep.
Can be tested specifying 
timestep.control=hardcoded and
timestep.control.filename=timesteps

Timestepper based on user input

---

opm/core/linalg/LinearSolverPetsc.cpp

- api changes in newer versions
- do not manually destroy the preconditioner. this is, and has always
been, owned by the ksp object and dies with its destruction.

update petsc code

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

Previously, we also called it when the full time step was done.
As the simulator writes that information anyway and we cannot call it a sub step, we omit the final write in the adaptive time stepper.
This is the patch proposed in OPM/opm-simulators#823. Closes OPM/opm-simulators#823.

Only call writeTimeStep for real sub steps.

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp

Some of the tuning values from the TUNING keywords is used to tune the
time-stepping instead of the equivalent ones in param_.
This only implements part of the TUNING keyword. (The ones that where already implemented in OPM) Even thought I don't have any immediate plans for extending the usage of TUNING in the simulator, using TUNING instead of specifying parameters directly saves me some time in my work.

Add contructor for adaptiveTimeStepper that uses values from TUNING

---

opm/core/utility/Units.hpp

as a bonus it avoids unused variable warnings in compile
units only using parts of the conversion units.
ref https://github.com/OPM/opm-parser/pull/893

changed: generate unit type conversion constants on compile-time

---

opm/core/simulator/initStateEquil.hpp
opm/core/simulator/initStateEquil_impl.hpp

the purpose of this is to get a more defined behaviour when doing the
gravity correction/upstream cell determination in the flux term.
I consider this to be just a kludge, so if anyone has a better idea of
what the composition for the non-existing gas and oil phases is,
please tell me. (note that generic compositional models do not exhibit
this issue because the composition of all fluids is always fully
defined because each component is assumed to dissolve in every phase.)
also be aware that this PR is independent of OPM/opm-simulators#845.

set the Rv and Rs factors to the saturated values for cells which have no gas and no oil

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

In parallel each breakdown of the solver was reported once for every process. WIth this commit we only do this logging on one process. Note that this patch is based on PR OPM/opm-common#179. Without each message will get logged twice.

Log the message of exceptions in the catch clause of adaptive time stepper

---

opm/core/props/satfunc/RelpermDiagnostics_impl.hpp

This snuck in without me noticing it in the units-merging-fest, I guess I should have noticed on Jenkins though. Sorry for any trouble, will self-merge to get this compiling again.

Undo premature API change adaption.

---

CMakeLists_files.cmake

CMakeLists_files.txt needed some adaptation after the recent unit
changes. this is analogous to OPM/opm-parser#943

fix `make install`

---

opm/core/props/satfunc/RelpermDiagnostics_impl.hpp

this broke because EclEpsScalingPointsInfo::extractScaled() now
requires the deck and the EclipseState as additional parameters.
this is required to fix the build once OPM/opm-material#169 has been merged.

RelpermDiagnostics: fix the build

---

opm/core/props/rock/RockCompressibility.cpp
opm/core/props/rock/RockCompressibility.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp

This should address the issue raised in OPM/opm-simulators#824.
Also (not directly related) ensures that logging is only happening on the first rank in a parallel run (the event it is fixed for is the rare event of complete breakdown of time-stepping).
Requires OPM/opm-common#185 (but not vice versa).

Convergence failure is "problem" not "error"

---

opm/core/wells/WellsManager.hpp

This PR replaces the initializer list on the constructor of WellsManager with the equally valid empty construction of objects. Otherwise the code won't compile without the c++14 flag which is not needed anywhere else.

Make WellsManager compile with c++-11.

---

opm/core/simulator/WellState.hpp

Adapt to vector -> map change.
Requires OPM/opm-output#116.

Adapt to changed data::Wells API.

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

Default is kept at -1.0. I.e. this PR does not change the current
behavior.
Useful for testing restarts.

Make it possible to set initial timestep

---

opm/core/simulator/WellState.hpp

This makes restart tests pass again. Please, sanity check, I'm on very thin grounds ;)

fixed: use correct indices for perforation pressure

---

opm/core/simulator/initState_impl.hpp

this fixes some valgrind errors which I found while doing the twophase capability for flow_ebos: In all previously tested cases, these errors were probably non-fatal because the memory illegally accessed here is likely to be allocated (but after this function was finished it contained garbage).
note that I'm not completely sure if this patch is semantically correct, so I'd appreciate some input who understands it. (what is a "z" anyway? I remember a computer game by that name, but that's definitely not it.)

fix some valgrind errors in the init code

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/SimulatorReport.cpp
opm/core/simulator/SimulatorReport.hpp

this allows the performance report at the end of the simulation to be more relevant. in particular, the time needed for linearization and that for linear solves is kept track independently.
note that to take advantage of this, the actual simulators need to use the new possibilities. that is done in a separate opm-simulators PR.

Improve simulator report

---

opm/core/simulator/AdaptiveTimeStepping_impl.hpp

that was a copy-and-pasto: newton iterations = linearizations - 1

AdaptiveTimeStepping: fix stupid (but harmless) mistake in the sub-step info message

---

opm/core/props/IncompPropertiesFromDeck.cpp
opm/core/props/pvt/PvtPropertiesIncompFromDeck.cpp
opm/core/props/pvt/PvtPropertiesIncompFromDeck.hpp

Read the PVTW table entries from EclipseState rather than manually
through the Deck object.

Read PVTW from EclipseState

---

tests/DuneIstlTestHelpers.hpp

some versions of boost seem to be more picky about this than others...

add missing semicolon to fix the build

---

opm/core/simulator/AdaptiveSimulatorTimer.cpp
opm/core/simulator/AdaptiveSimulatorTimer.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp
opm/core/simulator/SimulatorTimer.hpp
opm/core/simulator/SimulatorTimerInterface.hpp

Used in flow ebos to tell the simulator to recalculate the cached
quantities for failed time steps.

Store whether timestep failed or not

---

CMakeLists_files.cmake
opm/core/simulator/initStateEquil.hpp
opm/core/simulator/initStateEquil_impl.hpp
tests/capillarySwatinit.DATA
tests/test_equil.cpp

The reasoning behind this PR is to make it possible to initialize the case
without SWATINIT in order to compute the same defaulted THPRES values as
Ecl. The initialization needs to be re-computed to account for SWATINIT
in the simulations. But this is already the case in flow_ebos

Make it optinal to apply SWATINIT

---

opm/core/simulator/EquilibrationHelpers.hpp

Triggered by a new two-phase case.
It is not clear why the scalar solver fails to converge quickly in this case, but as it
- only affects the initialization
- can be easily addressed with no effect on any other cases
... it may not be worth spending a lot of time investigating it.

Increase max iterations for capillary curve inversion.

---

opm/core/linalg/ParallelIstlInformation.hpp

It does this using a mask vector with entries 0 or 1. If that is not provided
it falls back to std::accumulate.
This will be needed for the parallel flow_ebos.

Added an accumulate method that allows to switch off non-owner entries.

---

opm/core/wells/WellCollection.cpp
opm/core/wells/WellCollection.hpp
opm/core/wells/WellsGroup.cpp
opm/core/wells/WellsGroup.hpp

to provide a better standard for the wells under individual control to
return to group control. For example, some wells get really big group
control limit and switch to individual control, it is very difficult for
them to return to group control with that kind of unreasonable fixed
group limit.
It will be needed for the downstream opm-simulator development for the group control for flow-ebos.

updating the group control limit for individual control wells

---

opm/core/wells/WellsGroup.cpp

Not sure it is always the best thing to do here, while it can help the consistence of the two current controls in the well_controls and well_state, and also the individual_control_. 
It will be required by the incoming downstream group control PR in opm-simulators.

set the VREP control as current control when applying VREP control

---

opm/core/simulator/AdaptiveTimeStepping.hpp
opm/core/simulator/AdaptiveTimeStepping_impl.hpp

needed as substep summary reports requires FIP data to be available.
add calculation of this data if output is requested and summary config holds
relevant keywords.

changed: pass fipnum array into adaptive time stepping loop

---

opm/core/simulator/initStateEquil_impl.hpp

Makes the initial rs and rv values match the ecl values. 
The simulator independently sets Rs=rsSat and rv=rvSat for the saturated case. This should therefore not change any results. Only tested on Model 2 rel-0. 
Is this initialization code used by other simulators than flow and flow_ebos?

Do not set rs=rsSat and rv=rvSat for the saturated case

---

opm/core/simulator/WellState.hpp

When no THP target/limit is involved in the well control, we should not assign a non-zero value to the THP value.  It means, we will always output zero THP value for this well. 
It does not change previously matched results from the THP control case.

Fixing thp initialization

---

opm/core/simulator/EquilibrationHelpers.hpp
opm/core/utility/linearInterpolation.hpp

Makes initial rs values when outside depth range compatible with Ecl.

Do not extrapolate initial rs and rv values in the depth tables

---

tests/test_equil.cpp

As describeded here: https://github.com/OPM/opm-core/issues/1148 the PR: https://github.com/OPM/opm-parser/pull/1051 has broken the test of `EQUIL` in decks with `SWATINIT`. In opm-core - I really do not know how to fix this situation, and no one have stepped up to assist yet.
So - in agreement with @atgeirr I will merge this PR temporarily disabling the test if Travis goes green. Hopefully @totto82, @andlaus  or someone else with intimate knowledge of endscaling and `SWATINIT` can resolve the situation properly.
Sorry about the mess.

Temporarily disabled EQUIL + SWATINIT test.

---

opm/core/wells.h
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp
opm/core/wells/wells.c
tests/test_wells.cpp
tutorials/tutorial4.cpp

Note: -1 is used if default saturation table ids.
Depends on OPM/opm-parser#1045

Add sat table id to well struct

---

opm/core/props/satfunc/SaturationPropsFromDeck.cpp
opm/core/props/satfunc/SaturationPropsFromDeck.hpp

This adds the glue functions required to pass the hysteresis parameters for flow_legacy in and out of restart files.

Added functions in SaturationProps for hysteresis IO

---

opm/core/simulator/SimulatorReport.cpp
opm/core/simulator/SimulatorReport.hpp

the method can still be called as it used to be. in this case no failures are reported, though.

SimulatorReport: make it possible to report failed time steps

---

opm/core/wells/InjectionSpecification.cpp
opm/core/wells/ProductionSpecification.cpp
opm/core/wells/WellCollection.cpp
opm/core/wells/WellCollection.hpp
opm/core/wells/WellsGroup.cpp
opm/core/wells/WellsGroup.hpp
opm/core/wells/WellsManager.cpp
opm/core/wells/WellsManager.hpp
opm/core/wells/WellsManager_impl.hpp

The major reason for this PR is to help to fulfill the computation of the well potentials for each `time step` instead of using the well potentials from the end of `last report step`. As a result, setting the `guide rate` based on `well potentials` can be done in the initialization of the `WellsManager` anymore. 
And also, make the `distr` in `well_controls` recognize the injection phase. 
More description will be found in the PR description in the OPM/opm-simulators#1118.

[WIP] changes needed to compute well potentials each time step. 

---

opm/core/wells/well_controls.c

The Alq and vfp is set free in well_controls_destroy to avoid memory
leakage. Valgrind stopped complaining after this fix. 
@and Can you verify that this fixes the memory issue you reported.

FIX memory leakage in well_controls

---

opm/core/linalg/ParallelIstlInformation.hpp

some headers must be included unconditionally.
this patch should also go into the release branch.

fix non-MPI builds

---

opm/core/props/satfunc/SaturationPropsFromDeck.cpp

Remove warnings of uninitialized variables.

[cleanup] remove two uninitialized warnings in SaturationProposFromDeck.

---

opm/core/linalg/LinearSolverPetsc.cpp
opm/core/linalg/LinearSolverPetsc.hpp

to fix the compilation when PETsc exists.
This fixes the issue #1166.

removing the unused parameter:: for LinearSolverPetsc

---

opm/core/simulator/WellState.hpp

Useful if you don't have a ReservoirState

Add interface for passing cell pressures directly in wellState.init(...)

---

opm/core/wells/WellCollection.cpp

This fixes a case where no group control is specified for a group. 
For applying this patch to the SPE9 case:  
```
--- a/wells_test_suite/GROUP/SPE9_GROUP/SPE9_CP_GROUP.DATA
+++ b/wells_test_suite/GROUP/SPE9_GROUP/SPE9_CP_GROUP.DATA
@@ -432,8 +432,8 @@ WELSPECS
'INJE2 '  'A'  4  20  9110 'WATER'    60   /
'PRODU7 ' 'A'  4   6  9110 'OIL'      60   /
'PRODU9 ' 'A'  14  8  9110 'OIL'      60   /
- 'PRODU15' 'A'  11 14  9110 'OIL'      60   /
- 'PRODU23' 'A'  15 22  9110 'OIL'      60   /
+ 'PRODU15' 'B'  11 14  9110 'OIL'      60   /
+ 'PRODU23' 'B'  15 22  9110 'OIL'      60   /
/
```
This will fail in the current master. Since no control is specified for group B. 
But work with this patch.

Fix fallout if no group controll (NONE) is specified for a group

---

opm/core/utility/initHydroCarbonState.hpp

this allows it to be used in multiple compile units without the linker running amok.

mark initHydroCarbonState() as inline

---

opm/core/props/satfunc/RelpermDiagnostics_impl.hpp

Two checks were erroneously entered, based on a mix-up of which saturation to check. These are now removed. Simply run flow on the Norne deck to confirm.

Removing redundant checks from Nexus

---

opm/core/linalg/LinearSolverIstl.cpp
tests/DuneIstlTestHelpers.hpp
tests/test_linearsolver.cpp

We are targetting DUNE 2.4.* and 2.5.* currently. Therefore this commit removes
the if checks for lower versions to cleanup the code.

[cleanup] Removes unnecessary if clauses for unsupported DUNE versions.

---

examples/compute_initial_state.cpp
opm/core/simulator/EquilibrationHelpers.hpp
opm/core/simulator/initStateEquil.hpp
opm/core/simulator/initStateEquil_impl.hpp
tests/test_equil.cpp

This PR untangle the EQUIL initialization from opm-core legacy property, blackoilState and blackoilPhase objects.

Remove black oil props from init

---

opm/core/props/BlackoilPhases.hpp
opm/core/props/phaseUsageFromDeck.hpp

this adds a energy "phase" analogous to solvents and polymer to PhaseUsage. It also fixes a compiler warning which appears because the `Phase` class of opm-parser now has an 'ENERGY' enum.

Add energy phase

---

tests/test_wellsmanager.cpp

Fix the failed test due to https://github.com/OPM/opm-parser/pull/1168 .

fixing history mode tests
