OPM/opm-core

CMakeLists_files.cmake, examples/compute_eikonal_from_files.cpp, opm/core/tof/AnisotropicEikonal.cpp, opm/core/tof/AnisotropicEikonal.hpp, tests/test_anisotropiceikonal.cpp
The anisotropic Eikonal equation is:
grad(u)^T * M * grad(u) = 1
for some metric tensor M, that typically may vary in space.
This is currently used for making flow-diagnostic estimates of drained volume in the context of primary production, but could have numerous other uses.
The following limitations apply:
- This is only a 2d code. While the general approach should work in 3d, there are nontrivial details that have not been worked out yet. The code tests for this.
- The unit test is quite simple, and is a regression test rather than a truth test.
- Performance is not very impressive, but good enough to be useful for testing the method.
=> Solver for the anisotropic Eikonal equation using fast marching method

opm/core/io/eclipse/EclipseWriter.cpp, opm/core/wells/WellsManager.cpp
Renames due to: https://github.com/OPM/opm-parser/pull/394
=> Added WellCompletion namespace

opm/core/wells/WellsManager_impl.hpp
=> Added missing enum rename

opm/core/utility/thresholdPressures.hpp
This should fix: https://github.com/OPM/opm-parser/issues/396. The problem is default handling - that is seriously difficult to get Right&trade; The current approach is that:
1. All default values mentioned in the Json config should be sensible, i.e. use values like -1 to indicate default behavior should be avoided.
2. A `DeckItem` which does not have value (coming either from the deck or as a default) will throw an exception when you ask for the data - that was what happened here.
The clear ambition is that all these details should be handled 100% in the parser, and the external modules should only use the "fully processed" `EclipseState` object - that is probably the long term for this problem as well.
=> Protecting against use of unassigned deck values.

opm/core/simulator/AdaptiveSimulatorTimer.cpp, opm/core/simulator/AdaptiveSimulatorTimer.hpp, opm/core/simulator/AdaptiveTimeStepping_impl.hpp, opm/core/simulator/PIDTimeStepControl.cpp, opm/core/simulator/PIDTimeStepControl.hpp
This PR introduced a max growth factor for the timestep size as well as some fixes for the times step computatation and improvement of the output.
=> AdaptiveTimeStepping improvements.

opm/core/io/eclipse/EclipseWriter.cpp
[ Observe that this requires a screaming latest version of ERT ]
The original version of the code wrote 14 items per connection to the
ICON array, however when loading restart information the ERT well loader
currently expects to find segment information in item 15. Will now write
an additional segment id item for each connection.
In addition the code has been refactored to use operator[] to set
elements instead of push_back() which was used previously.
Have tested on Norne - works on my machine!
=> Fixed writing well information to the restart file

opm/core/wells/WellsManager_impl.hpp
[ Requires: https://github.com/OPM/opm-parser/pull/410 ]
Will use Value<double> for connection factor; that facilities asking the question `hasValue()`
=> Use Value<double> for Connection Factor

opm/core/grid/GridManager.cpp
PR https://github.com/OPM/opm-parser/pull/416 should be merged first.
=> Support minpvf.

opm/core/simulator/SimulatorReport.cpp, opm/core/simulator/SimulatorReport.hpp
This PR adds the number of newton and linear iterations to the report structure.
=> SimulatorReport: add total number of newton and linear iterations to report struct.

CMakeLists_files.cmake, opm/core/io/eclipse/EclipseWriteRFTHandler.cpp, opm/core/io/eclipse/EclipseWriteRFTHandler.hpp, opm/core/io/eclipse/EclipseWriter.cpp, opm/core/io/eclipse/EclipseWriter.hpp, tests/test_EclipseWriteRFTHandler.cpp
Added writing of eclipse RFT file to EclipseWriter. The writing of RFT data is handled in a separate class, EclipseWriteRFTHandler.
=> OPM 157 write RFT data

tests/test_writenumwells.cpp
Followup to: https://github.com/OPM/opm-parser/pull/398
=> Not creating Logger instance explicitly.

opm/core/io/eclipse/EclipseWriter.cpp, opm/core/props/pvt/ThermalGasPvtWrapper.hpp, opm/core/props/pvt/ThermalOilPvtWrapper.hpp, opm/core/props/pvt/ThermalWaterPvtWrapper.hpp
More warning suppression. With this opm-core compiles cleanly at high warning levels.
=> Suppress warnings

cmake/Modules/opm-autodiff-prereqs.cmake
Manually imported from opm-autodiff.
=> Update Eigen requirements.

opm/core/simulator/AdaptiveTimeStepping_impl.hpp
Added dune/istl/istlexception.hh
=> Fix to make current master compile with dune-istl 2.2

opm/core/io/eclipse/EclipseWriter.cpp
This is a fixup to: https://github.com/OPM/opm-core/pull/788
=> Ert function ecl_sum_add_tstep() expects seconds.

opm/core/simulator/AdaptiveTimeStepping_impl.hpp
I would appreciate if @dr-robertk or @totto82 could review and check this PR and OPM/opm-autodiff#362.
=> Modify default parameters to be suitable for the Norne case.

redhat/opm-core.spec
A version bump pull will follow after backports to release branch has been done.
=> update redhat packaging

CMakeLists.txt
- requires https://github.com/OPM/opm-cmake/pull/12 for a fully working build.
=> changed: locate opm-cmake using config mode

opm/core/io/eclipse/EclipseWriter.cpp
Depending on : https://github.com/OPM/opm-parser/pull/468
=> Added suport for converting of Metric grid values

opm/core/linalg/ParallelIstlInformation.hpp, opm/core/simulator/TimeStepControl.hpp, opm/core/utility/platform_dependent/disable_warnings.h, tests/DuneIstlTestHelpers.hpp, tests/test_parallelistlinformation.cpp
Also add more warnings to the disabling list of disable_warnings.h.
=> Silence multiple warnings.

opm/core/io/eclipse/EclipseWriter.cpp
As discovered by @andlaus and @bska
=> Added missing free( ) to malloc() memory.

CMakeLists_files.cmake, opm/core/io/eclipse/EclipseReader.cpp, opm/core/io/eclipse/EclipseReader.hpp, opm/core/io/eclipse/EclipseWriter.cpp, opm/core/simulator/WellState.hpp, tests/test_readWriteWellStateData.cpp
Added read and write of RESTART wellstate data.
This task is a step towards supporting RESTART functionality in Flow. 
The task is "self-contained", not dependent on other tasks.
=> Opm 188 Read and write of RESTART wellstate data

opm/core/simulator/WellState.hpp
=> Add missing include statement.

opm/core/props/satfunc/SatFuncMultiplexer.hpp, opm/core/simulator/ExplicitArraysFluidState.hpp
This restores a warning-free build for me.
=> Fix unused argument warnings.

CMakeLists_files.cmake, opm/core/grid.h, opm/core/grid/grid.c, opm/core/utility/memcmp_double.c, opm/core/utility/memcmp_double.h, tests/test_ug.cpp
Very small utility for comparing two C double * vectors.
=> Added small utility memcmp_double()

opm/core/utility/thresholdPressures.hpp
Dependent on : https://github.com/OPM/opm-parser/pull/562.
=> Threshold pressure

CMakeLists_files.cmake, opm/core/utility/thresholdPressures.hpp, tests/test_thresholdpressure.cpp
Followup to: https://github.com/OPM/opm-parser/pull/565
=> Using map base ThresholdPressure implementation.

opm/core/props/pvt/BlackoilPvtProperties.cpp, opm/core/props/pvt/ThermalGasPvtWrapper.hpp, opm/core/props/pvt/ThermalOilPvtWrapper.hpp, opm/core/props/pvt/ThermalWaterPvtWrapper.hpp, opm/core/props/rock/RockCompressibility.cpp, opm/core/props/satfunc/SatFuncBase.hpp, opm/core/props/satfunc/SaturationPropsFromDeck_impl.hpp, opm/core/simulator/initStateEquil.hpp, tests/test_blackoilfluid.cpp
Followup to: https://github.com/OPM/opm-parser/pull/570
=> Using TableManager to get tables.

opm/core/grid/GridHelpers.hpp, opm/core/props/pvt/PvtDead.cpp, opm/core/props/pvt/PvtDeadSpline.cpp, opm/core/props/pvt/PvtLiveOil.cpp, opm/core/props/pvt/ThermalGasPvtWrapper.hpp, opm/core/simulator/initStateEquil.hpp, tests/test_geom2d.cpp
This fixes several warnings in core about shadowed variables / functions. Should have no other side effects
=> Fixed several warnings

opm/core/props/BlackoilPropertiesFromDeck.cpp
Also, some trailing white spaces are removed.
=> [BlackoilPropsFromDeck] remove sign/unsigned warnings.

opm/core/simulator/initStateEquil_impl.hpp
=> Support for equil-initialisation for datum depth outside oil zone.

opm/core/grid/MinpvProcessor.hpp
This fix relates to https://github.com/OPM/opm-core/issues/898
=> fix actnum with cartesian grid issue.

opm/core/props/pvt/PvtLiveGas.cpp
This PR copies equivalent code from PvtLiveOil
=> Complete undersaturated PVTG tables by extrapolating from existing data

examples/sim_2p_incomp.cpp, opm/core/props/satfunc/SaturationPropsFromDeck.cpp
This PR makes two-phase runs with sim_2p_incomp work again as intended.
=> Fix twophase sim

tests/test_pinchprocessor.cpp, tests/test_relpermdiagnostics.cpp
This is a trivial PR, will self-merge.
=> Silence warnings in test programs.

opm/core/props/pvt/PvtDead.cpp, opm/core/props/pvt/PvtDeadSpline.cpp, opm/core/props/pvt/PvtLiveGas.cpp, opm/core/props/pvt/PvtLiveOil.cpp, opm/core/props/rock/RockCompressibility.cpp, opm/core/props/satfunc/RelpermDiagnostics.cpp, opm/core/simulator/initStateEquil.hpp, opm/core/utility/NonuniformTableLinear.hpp, tests/test_norne_pvt.cpp
See: https://github.com/OPM/opm-parser/pull/649
=> Table column

examples/mirror_grid.cpp, examples/sim_2p_incomp.cpp, opm/core/grid/GridManager.cpp, opm/core/io/eclipse/EclipseGridInspector.cpp, opm/core/io/eclipse/EclipseReader.cpp, opm/core/io/eclipse/EclipseWriter.cpp, opm/core/props/IncompPropertiesSinglePhase.cpp, opm/core/props/pvt/PvtConstCompr.hpp, opm/core/props/pvt/PvtInterface.hpp, opm/core/props/pvt/PvtPropertiesIncompFromDeck.cpp, tests/test_EclipseWriter.cpp, tests/test_parser.cpp, tests/test_pinchprocessor.cpp, tests/test_timer.cpp, tests/test_ug.cpp, tests/test_wellcollection.cpp, tests/test_wellsgroup.cpp
Adopting to opm-parser PR#661, add previously missing includes.
https://github.com/OPM/opm-parser/pull/661
=> Improve includes from opm-parser

opm/core/simulator/SimulatorState.cpp, opm/core/simulator/SimulatorState.hpp
OK - these commits should completely revert: #948. I'm really sorry for the #948 - I f...ed up:
=> Build fixup

.travis.yml, README.md, travis/build-and-test-opm-core.sh, travis/build-opm-core.sh, travis/clone-and-build-dune-istl.sh, travis/clone-and-build-superlu.sh
Added support for TravisCI.
Renamed README to README.md and added build status image.
=> Travis support

opm/core/io/eclipse/EclipseWriter.cpp, opm/core/props/satfunc/SaturationPropsFromDeck.cpp
These files have been removed upstream.
=> Remove unused Wrapper includes from Deck/Utility

opm/core/grid/grid_equal.cpp, opm/core/simulator/BlackoilState.cpp, opm/core/simulator/SimulatorState.cpp
Followup to: https://github.com/OPM/opm-common/pull/77
=> Using template for cmp::vector_equal()

opm/core/simulator/initStateEquil.hpp, opm/core/wells/WellsManager_impl.hpp
opm-parser pull #695
https://github.com/OPM/opm-parser/pull/695
Can be merged before upstream.
=> Add missing opm-parser headers

opm/core/simulator/SimulatorState.cpp
After this my compile is warning free, except a minor issue with SimulatorTimer (PR will follow).
=> Silence sign comparison warning.

examples/diagnose_relperm.cpp
If the deck file is **XXX.DATA**, output log file will be **XXX.LOG** in the same directory.
=> use standard filename for output log file.

CMakeLists_files.cmake, examples/diagnose_relperm.cpp, opm/core/props/satfunc/RelpermDiagnostics.cpp, opm/core/props/satfunc/RelpermDiagnostics.hpp, opm/core/props/satfunc/RelpermDiagnostics_impl.hpp, tests/test_relpermdiagnostics.cpp
See comments in https://github.com/OPM/opm-autodiff/pull/593
=> make grid as template parameter.

opm/core/props/BlackoilPropertiesFromDeck.cpp
the dissolution factors used for the viscosities were always zero so
far. this was not discovered earlier because flow is completely
unaffected by this since the only place where this class is in flow is
the equilibration code and the equilibration code does not need the
phase viscosities.
thanks to @atgeirr for finding this.
=> BlackoilPropertiesFromDeck: properly calculate the Rs and Rv values for viscosity

opm/core/utility/thresholdPressures.hpp
the typo was caused the surface density of the oil phase to be used
instead of the one of gas. This caused the density to be off by a
factor of typically about 900.
using saturated FVFs does not change much, but it does not hurt
because it is also done that way in the simulator.
This makes the defaults for the threshold pressures reasonable again,
but for some reason they are not exactly the same as in the old
implementation. (although the differences are very tolerable.)
On the question why only "Model 2" is affected by this: the other
decks don't use threshold pressures (SPE-X) or do not default any
values (Norne).
=> threshold pressures: consider the saturated case and fix a typo

examples/compute_initial_state.cpp, examples/compute_tof.cpp, examples/diagnose_relperm.cpp, examples/mirror_grid.cpp, examples/sim_2p_comp_reorder.cpp, examples/sim_2p_incomp.cpp, examples/wells_example.cpp, opm/core/io/eclipse/CornerpointChopper.hpp, tests/test_EclipseWriteRFTHandler.cpp, tests/test_EclipseWriter.cpp, tests/test_blackoilstate.cpp, tests/test_column_extract.cpp, tests/test_compressedpropertyaccess.cpp, tests/test_equil.cpp, tests/test_norne_pvt.cpp, tests/test_parser.cpp, tests/test_pinchprocessor.cpp, tests/test_relpermdiagnostics.cpp, tests/test_satfunc.cpp, tests/test_stoppedwells.cpp, tests/test_thresholdpressure.cpp, tests/test_timer.cpp, tests/test_ug.cpp, tests/test_wellcollection.cpp, tests/test_wellsgroup.cpp, tests/test_wellsmanager.cpp, tests/test_writeReadRestartFile.cpp, tests/test_writenumwells.cpp
Depend on https://github.com/OPM/opm-parser/pull/719  and https://github.com/OPM/opm-material/pull/134
=> Rename parse mode

opm/core/wells/ProductionSpecification.hpp, opm/core/wells/WellsManager.cpp, opm/core/wells/WellsManager.hpp, opm/core/wells/WellsManager_impl.hpp
The default guide rates are calculated using the well potentials.
The well potentials are calculated in the simulator and given as input
to the wellsManager.
=> Calculate default guide rates using the well potentials

jenkins/README.md, jenkins/build-opm-core.sh, jenkins/build-pr.sh, jenkins/build.sh
This is the build scripts for this module, ref OPM/opm-common#102 and OPM/opm-parser#743
=> Jenkins reboot

opm/core/props/phaseUsageFromDeck.hpp, opm/core/props/rock/RockCompressibility.cpp, opm/core/props/rock/RockFromDeck.cpp, opm/core/props/satfunc/RelpermDiagnostics.cpp, opm/core/props/satfunc/RelpermDiagnostics_impl.hpp, opm/core/simulator/initStateEquil.hpp, opm/core/utility/CompressedPropertyAccess.hpp, opm/core/utility/extractPvtTableIndex.cpp, opm/core/utility/thresholdPressures.hpp, tests/test_pinchprocessor.cpp
This pull request uses the Eclipse3DProperties API from opm-parser.
CompressedPropertyAccess.hpp needs a thorough read-through before merge.
Ref OPM/opm-parser#751
=> Use Eclipse3DProperties

opm/core/props/satfunc/RelpermDiagnostics.cpp
Remove the left ``Error`` prefix.
=> Cleanup the prefix.

opm/core/simulator/AdaptiveSimulatorTimer.cpp, opm/core/simulator/AdaptiveTimeStepping_impl.hpp
Log timer messages to log file.
=> Log timer messages

opm/core/props/rock/RockCompressibility.cpp, opm/core/utility/parameters/ParameterGroup_impl.hpp, opm/core/wells/InjectionSpecification.cpp, opm/core/wells/InjectionSpecification.hpp, opm/core/wells/ProductionSpecification.cpp, opm/core/wells/ProductionSpecification.hpp, opm/core/wells/WellsGroup.cpp, opm/core/wells/WellsManager_impl.hpp
summary:
- Add enum to string functions for injection and production specification.
- log well-related information 
- log information in parameter group
- some other information.
=> Write more messages into OpmLog.

opm/core/props/BlackoilPropertiesFromDeck.cpp, opm/core/simulator/ExplicitArraysSatDerivativesFluidState.hpp
this is the opm-core part of OPM/opm-material#147. the PR must be merged in lockstep lest there be breakage...
=> rename "local AD" to "dense AD"

opm/core/props/rock/RockCompressibility.cpp, opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
- Output file name and line number when the deck has more than 1 region of the values.
- Add a blank line before ``***************Saturation Functions Diagnostics***************``
=> Format message

.travis.yml, CMakeLists_files.cmake, opm/core/simulator/AdaptiveTimeStepping.hpp, opm/core/simulator/AdaptiveTimeStepping_impl.hpp, opm/core/simulator/BlackoilState.cpp, opm/core/simulator/WellState.hpp, opm/core/utility/Compat.hpp
See https://github.com/OPM/opm-output/pull/30
=> Breaking opm-core dependency in opm-output; new summary implementation

opm/core/linalg/LinearSolverFactory.cpp
This reverts commit f54c74db0637640f5fb224fab243b294cd034f15.
This fix is wrong.
=> Revert "Check for HAVE_UMFPACK in LinearSolverFactory"

opm/core/props/rock/RockCompressibility.cpp
For a message which is more than one line, it is better to add "\n" at the end of the message.
=> Minor format changes

opm/core/linalg/LinearSolverFactory.cpp
Partially adresses issue #1036. Still possible to fail if you have *no* linear solver available (but that should rather be the build system's job to intercept).
=> Set default solver depending on configuration.

opm/core/simulator/initStateEquil.hpp
Eclipse output this equilibration check.
=> Rise up a warning if equil region has no active cells.

opm/core/simulator/AdaptiveTimeStepping_impl.hpp, opm/core/simulator/SimulatorTimer.cpp, opm/core/simulator/SimulatorTimer.hpp
- Change adaptive time stepping messages type to OpmLog::note
- Let SimulatorTime return current date time
=> Change adaptive time stepping message type to OpmLog::note

CMakeLists_files.cmake, opm/core/simulator/SimulatorTimer.cpp, opm/core/simulator/SimulatorTimer.hpp, opm/core/wells/DynamicListEconLimited.hpp, opm/core/wells/WellsManager.cpp, opm/core/wells/WellsManager.hpp, opm/core/wells/WellsManager_impl.hpp, opm/core/wells/wells.c
Basically, according to economic check based on the production behavior, we need to stop/shut of some non-economical wells or completions. 
The part in opm-core is trying to support this mechanism and the downstream PR in opm-simulator is comings soon too.
=> Support of the keyword WECON

opm/core/simulator/AdaptiveTimeStepping_impl.hpp
Adapt to the changes in https://github.com/OPM/opm-simulators/pull/758
=> Drop useage of std::numeric_limits

opm/core/simulator/SimulatorReport.cpp, opm/core/simulator/SimulatorReport.hpp
=> also keep track of the number of linearizations needed for the simulation

jenkins/build-opm-core.sh, jenkins/build-pr.sh, jenkins/build.sh
Depends on https://github.com/OPM/opm-common/pull/168
=> simplify jenkins build scripts after ert reorganization

opm/core/simulator/AdaptiveTimeStepping_impl.hpp
Enables outputting cell data to UNRST files.
See also sibling pull requests in OPM/opm-simulators#805 and OPM/opm-output#84
=> Output writer cell data

opm/core/props/satfunc/RelpermDiagnostics.cpp, opm/core/simulator/WellState.hpp
After this, opm-core compiles warning-less for me.
=> Fix a few warnings

opm/core/wells/WellCollection.cpp, opm/core/wells/WellCollection.hpp, opm/core/wells/WellsGroup.cpp, opm/core/wells/WellsGroup.hpp, opm/core/wells/WellsManager_impl.hpp, tests/test_wellcollection.cpp, tests/test_wellsgroup.cpp
https://github.com/OPM/opm-parser/pull/930
=> Schedule::getGroup returns reference, not pointer

redhat/opm-core.spec
=> update redhat6 packaging

opm/core/simulator/BlackoilState.cpp, opm/core/simulator/WellState.hpp
Followup to: https://github.com/OPM/opm-output/pull/101
=> Header file moved in opm-output.

opm/core/props/satfunc/RelpermDiagnostics.cpp
Noticed while doing OPM/opm-simulators#878.
@qilicun can you verify this?
=> Fix saturation family diagnostics for two-phase case.

opm/core/props/BlackoilPropertiesFromDeck.cpp, opm/core/props/satfunc/SaturationPropsFromDeck.cpp, opm/core/simulator/ExplicitArraysSatDerivativesFluidState.hpp
=> use accessor methods to access the value and derivatives of Evaluation objects

opm/core/props/phaseUsageFromDeck.hpp, opm/core/wells/WellsGroup.cpp
Downstream of https://github.com/OPM/opm-parser/pull/958
=> Read phase information from EclipseState.runspec

tests/test_equil.cpp
Downstream of https://github.com/OPM/opm-parser/pull/950
=> Use new DeckItem constructor interface.

opm/core/wells/WellsManager.cpp, opm/core/wells/WellsManager.hpp, opm/core/wells/WellsManager_impl.hpp, tests/test_wellcollection.cpp, tests/test_wellsgroup.cpp
Updates to the slightly modified GroupTree interface from opm-parser.
Downstream of https://github.com/OPM/opm-core/pull/1101
=> GroupTree interface changed upstream

opm/core/wells/WellCollection.cpp, opm/core/wells/WellCollection.hpp
with assuming we should always find the well in the well collection.
=> rewriting the findWellNode function

opm/core/wells/WellCollection.cpp, opm/core/wells/WellCollection.hpp, opm/core/wells/WellsManager_impl.hpp
And also, when adding WellNode to WellCollection, considering whether the well exists on this process.
=> Adding a flag to WellCollection whether group control active

opm/core/wells/WellsManager_impl.hpp
Downstream of https://github.com/OPM/opm-parser/pull/987
=> Ask for reference depth at timestep.

jenkins/build.sh
=> update jenkins dependency graph

opm/core/props/IncompPropertiesSinglePhase.cpp, opm/core/simulator/initState.hpp, opm/core/simulator/initState_impl.hpp
Prefer reading these values from EclipseState rather than the Deck type.
=> Read RS,RV,PRESSURE,SWAT,SGAS from EclipseState

opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Necessary after OPM/opm-material#191.
=> Remove unused Deck function argument.

examples/wells_example.cpp, opm/core/props/rock/RockCompressibility.cpp, opm/core/props/rock/RockCompressibility.hpp
Requires https://github.com/OPM/opm-parser/pull/1013
=> Read ROCK from EclipseState, not Deck

opm/core/props/rock/RockFromDeck.cpp, opm/core/props/satfunc/RelpermDiagnostics.cpp, opm/core/props/satfunc/RelpermDiagnostics.hpp, opm/core/props/satfunc/RelpermDiagnostics_impl.hpp
Prefer using EclipseState over Deck.
=> Don't rely on Deck for checkTable and checkPhase

opm/core/props/IncompPropertiesSinglePhase.cpp, opm/core/props/pvt/PvtPropertiesIncompFromDeck.cpp
Requires https://github.com/OPM/opm-parser/pull/1013
=> Use Density from EclipseState

opm/core/wells/WellsGroup.cpp
=> Throw if solvent phase injected.

tests/capillarySwatinit.DATA, tests/test_equil.cpp
This should fix the test. 
See issue #1148 
This PR also undo #1149
=> Fix test equil

debian/rules, redhat/opm-core.spec
Backports from 2017.04 release branch.
=> disable native tuning in packaging

opm/core/props/BlackoilPhases.hpp, opm/core/props/phaseUsageFromDeck.hpp, opm/core/simulator/BlackoilState.cpp, opm/core/simulator/BlackoilState.hpp
1) Add has_solvent to phase_usage 
2) Add solvent saturation to BlackoilState
=> Implement solvent model in flow_ebos

tests/test_pinchprocessor.cpp
Donstream of: https://github.com/OPM/opm-parser/pull/1132
=> Updated NNC() constructor.

tests/test_equil.cpp
Depends on OPM/opm-material#248
=> Update the swatinit test base on fix in opm-material#248

examples/compute_tof.cpp, opm/core/wells/WellsManager.cpp, opm/core/wells/WellsManager.hpp, opm/core/wells/WellsManager_impl.hpp, tests/test_stoppedwells.cpp, tests/test_wellcollection.cpp, tests/test_wellsgroup.cpp, tests/test_wellsmanager.cpp
Followup to: https://github.com/OPM/opm-parser/pull/1138
=> Updated NNC() constructor arguments.

opm/core/wells/WellsGroup.cpp, tests/test_wellcollection.cpp, tests/test_wellsgroup.cpp, tests/wells_group.data
Added test combining WEFAC and GEFAC
Depends on OPM/opm-parser#1156
=> Handle WEFAC

opm-core-prereqs.cmake
Upstream: https://github.com/OPM/opm-common/pull/304
=> changed: put prereqs in module itself

opm/core/utility/NonuniformTableLinear.hpp, opm/core/utility/SparseVector.hpp
Two minor fixes required before the utilities in question can be moved to opm-common.
=> Utility fixes
